export const ContractsVersionsDefaultName = 'contracts-versions'
export const SnapshotDirectory = 'src/versions'
export const SnapshotTrailingTag = 'snapshot'
export const SnapshotTagDelimiter = '.'
export const SnapshotNameExtension = 'json'
