/* eslint-disable camelcase */
import { lazy } from '@loadable/component'

export const aave_cbETH_usdc = lazy.lib(() => import('../../../tokens/icons/aave_cbETH_usdc'))
export const aave_circle_color = lazy.lib(() => import('../../../tokens/icons/aave_circle_color'))
export const aave_eth_usdc = lazy.lib(() => import('../../../tokens/icons/aave_eth_usdc'))
export const aave_steth_eth = lazy.lib(() => import('../../../tokens/icons/aave_steth_eth'))
export const aave_steth_usdc = lazy.lib(() => import('../../../tokens/icons/aave_steth_usdc'))
export const aave_wbtc_usdc = lazy.lib(() => import('../../../tokens/icons/aave_wbtc_usdc'))
export const aero = lazy.lib(() => import('../../../tokens/icons/aero'))
export const ajna_circle_color = lazy.lib(() => import('../../../tokens/icons/ajna_circle_color'))
export const apxeth_circle_color = lazy.lib(
  () => import('../../../tokens/icons/apxeth_circle_color'),
)
export const arb = lazy.lib(() => import('../../../tokens/icons/arb'))
export const arb_circle = lazy.lib(() => import('../../../tokens/icons/arb_circle'))
export const augur = lazy.lib(() => import('../../../tokens/icons/augur'))
export const augur_circle_color = lazy.lib(() => import('../../../tokens/icons/augur_circle_color'))
export const augur_color = lazy.lib(() => import('../../../tokens/icons/augur_color'))
export const bal = lazy.lib(() => import('../../../tokens/icons/bal'))
export const bal_circle = lazy.lib(() => import('../../../tokens/icons/bal_circle'))
export const bal_circle_color = lazy.lib(() => import('../../../tokens/icons/bal_circle_color'))
export const bat = lazy.lib(() => import('../../../tokens/icons/bat'))
export const bat_circle_color = lazy.lib(() => import('../../../tokens/icons/bat_circle_color'))
export const bat_color = lazy.lib(() => import('../../../tokens/icons/bat_color'))
export const bridge = lazy.lib(() => import('../../../tokens/icons/bridge'))
export const btc_circle_color = lazy.lib(() => import('../../../tokens/icons/btc_circle_color'))
export const btc_circle_mono = lazy.lib(() => import('../../../tokens/icons/btc_circle_mono'))
export const cbeth_circle_color = lazy.lib(() => import('../../../tokens/icons/cbeth_circle_color'))
export const cbeth_eth = lazy.lib(() => import('../../../tokens/icons/cbeth_eth'))
export const cbeth_usdc = lazy.lib(() => import('../../../tokens/icons/cbeth_usdc'))
export const chai = lazy.lib(() => import('../../../tokens/icons/chai'))
export const chai_circle_color = lazy.lib(() => import('../../../tokens/icons/chai_circle_color'))
export const chai_color = lazy.lib(() => import('../../../tokens/icons/chai_color'))
export const chainlink = lazy.lib(() => import('../../../tokens/icons/chainlink'))
export const chainlink_circle_color = lazy.lib(
  () => import('../../../tokens/icons/chainlink_circle_color'),
)
export const chainlink_color = lazy.lib(() => import('../../../tokens/icons/chainlink_color'))
export const compound = lazy.lib(() => import('../../../tokens/icons/compound'))
export const compound_circle_color = lazy.lib(
  () => import('../../../tokens/icons/compound_circle_color'),
)
export const compound_color = lazy.lib(() => import('../../../tokens/icons/compound_color'))
export const crv = lazy.lib(() => import('../../../tokens/icons/crv'))
export const crv_circle = lazy.lib(() => import('../../../tokens/icons/crv_circle'))
export const cseth = lazy.lib(() => import('../../../tokens/icons/cseth'))
export const dai = lazy.lib(() => import('../../../tokens/icons/dai'))
export const dai_circle_color = lazy.lib(() => import('../../../tokens/icons/dai_circle_color'))
export const dai_color = lazy.lib(() => import('../../../tokens/icons/dai_color'))
export const degen = lazy.lib(() => import('../../../tokens/icons/degen'))
export const not_supported_icon = lazy.lib(() => import('../../../tokens/icons/not_supported_icon'))
export const deth = lazy.lib(() => import('../../../tokens/icons/deth'))
export const digix_circle_color = lazy.lib(() => import('../../../tokens/icons/digix_circle_color'))
export const ena = lazy.lib(() => import('../../../tokens/icons/ena'))
export const eth_circle_color = lazy.lib(() => import('../../../tokens/icons/eth_circle_color'))
export const eth_circle_mono = lazy.lib(() => import('../../../tokens/icons/eth_circle_mono'))
export const eth_usdc = lazy.lib(() => import('../../../tokens/icons/eth_usdc'))
export const ether = lazy.lib(() => import('../../../tokens/icons/ether'))
export const ether_circle_color = lazy.lib(() => import('../../../tokens/icons/ether_circle_color'))
export const ether_color = lazy.lib(() => import('../../../tokens/icons/ether_color'))
export const euro_circle_color = lazy.lib(() => import('../../../tokens/icons/euro_circle_color'))
export const exchange = lazy.lib(() => import('../../../tokens/icons/exchange'))
export const ezeth = lazy.lib(() => import('../../../tokens/icons/ezeth'))
export const frax_circle_color = lazy.lib(() => import('../../../tokens/icons/frax_circle_color'))
export const gemini = lazy.lib(() => import('../../../tokens/icons/gemini'))
export const gemini_circle_color = lazy.lib(
  () => import('../../../tokens/icons/gemini_circle_color'),
)
export const gemini_color = lazy.lib(() => import('../../../tokens/icons/gemini_color'))
export const gho_circle_color = lazy.lib(() => import('../../../tokens/icons/gho_circle_color'))
export const gno_circle_color = lazy.lib(() => import('../../../tokens/icons/gno_circle_color'))
export const golem_circle_color = lazy.lib(() => import('../../../tokens/icons/golem_circle_color'))
export const guniv3_dai_usdc1_circles_color = lazy.lib(
  () => import('../../../tokens/icons/guniv3_dai_usdc1_circles_color'),
)
export const gusd_circle_color = lazy.lib(() => import('../../../tokens/icons/gusd_circle_color'))
export const gusd_circle_mono = lazy.lib(() => import('../../../tokens/icons/gusd_circle_mono'))
export const knc_circle_color = lazy.lib(() => import('../../../tokens/icons/knc_circle_color'))
export const kyber = lazy.lib(() => import('../../../tokens/icons/kyber'))
export const kyber_circle_color = lazy.lib(() => import('../../../tokens/icons/kyber_circle_color'))
export const kyber_color = lazy.lib(() => import('../../../tokens/icons/kyber_color'))
export const latamex = lazy.lib(() => import('../../../tokens/icons/latamex'))
export const ldo = lazy.lib(() => import('../../../tokens/icons/ldo'))
export const ldo_circle = lazy.lib(() => import('../../../tokens/icons/ldo_circle'))
export const link = lazy.lib(() => import('../../../tokens/icons/link'))
export const link_circle_color = lazy.lib(() => import('../../../tokens/icons/link_circle_color'))
export const link_circle_mono = lazy.lib(() => import('../../../tokens/icons/link_circle_mono'))
export const lrc = lazy.lib(() => import('../../../tokens/icons/lrc'))
export const lrc_circle_color = lazy.lib(() => import('../../../tokens/icons/lrc_circle_color'))
export const lrc_color = lazy.lib(() => import('../../../tokens/icons/lrc_color'))
export const lusd_circle_color = lazy.lib(() => import('../../../tokens/icons/lusd_circle_color'))
export const maker = lazy.lib(() => import('../../../tokens/icons/maker'))
export const maker_circle_color = lazy.lib(() => import('../../../tokens/icons/maker_circle_color'))
export const maker_color = lazy.lib(() => import('../../../tokens/icons/maker_color'))
export const mana = lazy.lib(() => import('../../../tokens/icons/mana'))
export const mana_circle_color = lazy.lib(() => import('../../../tokens/icons/mana_circle_color'))
export const mana_circle_mono = lazy.lib(() => import('../../../tokens/icons/mana_circle_mono'))
export const mana_color = lazy.lib(() => import('../../../tokens/icons/mana_color'))
export const matic_circle_color = lazy.lib(() => import('../../../tokens/icons/matic_circle_color'))
export const matic_circle_mono = lazy.lib(() => import('../../../tokens/icons/matic_circle_mono'))
export const meveth = lazy.lib(() => import('../../../tokens/icons/meveth'))
export const mkr_circle_color = lazy.lib(() => import('../../../tokens/icons/mkr_circle_color'))
export const moonpay = lazy.lib(() => import('../../../tokens/icons/moonpay'))
export const morpho_circle_color = lazy.lib(
  () => import('../../../tokens/icons/morpho_circle_color'),
)
export const mpeth = lazy.lib(() => import('../../../tokens/icons/mpeth'))
export const omisego = lazy.lib(() => import('../../../tokens/icons/omisego'))
export const omisego_circle_color = lazy.lib(
  () => import('../../../tokens/icons/omisego_circle_color'),
)
export const omisego_color = lazy.lib(() => import('../../../tokens/icons/omisego_color'))
export const op = lazy.lib(() => import('../../../tokens/icons/op'))
export const op_circle = lazy.lib(() => import('../../../tokens/icons/op_circle'))
export const open_in_new_tab = lazy.lib(() => import('../../../tokens/icons/open_in_new_tab'))
export const oseth_circle_color = lazy.lib(() => import('../../../tokens/icons/oseth_circle_color'))
export const pax = lazy.lib(() => import('../../../tokens/icons/pax'))
export const pax_circle_color = lazy.lib(() => import('../../../tokens/icons/pax_circle_color'))
export const pax_color = lazy.lib(() => import('../../../tokens/icons/pax_color'))
export const prime = lazy.lib(() => import('../../../tokens/icons/prime'))
export const pyusd = lazy.lib(() => import('../../../tokens/icons/pyusd'))
export const question = lazy.lib(() => import('../../../tokens/icons/question'))
export const question_mark = lazy.lib(() => import('../../../tokens/icons/question_mark'))
export const question_o = lazy.lib(() => import('../../../tokens/icons/question_o'))
export const rbn_circle_color = lazy.lib(() => import('../../../tokens/icons/rbn_circle_color'))
export const renbtc_circle_color = lazy.lib(
  () => import('../../../tokens/icons/renbtc_circle_color'),
)
export const reth_circle_color = lazy.lib(() => import('../../../tokens/icons/reth_circle_color'))
export const reth_eth = lazy.lib(() => import('../../../tokens/icons/reth_eth'))
export const reth_usdc = lazy.lib(() => import('../../../tokens/icons/reth_usdc'))
export const rpl = lazy.lib(() => import('../../../tokens/icons/rpl'))
export const rpl_circle = lazy.lib(() => import('../../../tokens/icons/rpl_circle'))
export const safe = lazy.lib(() => import('../../../tokens/icons/safe'))
export const sai = lazy.lib(() => import('../../../tokens/icons/sai'))
export const sai_circle_color = lazy.lib(() => import('../../../tokens/icons/sai_circle_color'))
export const sai_color = lazy.lib(() => import('../../../tokens/icons/sai_color'))
export const sdai_circle_color = lazy.lib(() => import('../../../tokens/icons/sdai_circle_color'))
export const snx = lazy.lib(() => import('../../../tokens/icons/snx'))
export const spark_circle_color = lazy.lib(() => import('../../../tokens/icons/spark_circle_color'))
export const steth_circle_color = lazy.lib(() => import('../../../tokens/icons/steth_circle_color'))
export const steth_eth = lazy.lib(() => import('../../../tokens/icons/steth_eth'))
export const steth_usdc = lazy.lib(() => import('../../../tokens/icons/steth_usdc'))
export const styeth_circle_color = lazy.lib(
  () => import('../../../tokens/icons/styeth_circle_color'),
)
export const susd = lazy.lib(() => import('../../../tokens/icons/susd'))
export const susd_circle = lazy.lib(() => import('../../../tokens/icons/susd_circle'))
export const susde = lazy.lib(() => import('../../../tokens/icons/susde'))
export const tbtc_circle_color = lazy.lib(() => import('../../../tokens/icons/tbtc_circle_color'))
export const tusd = lazy.lib(() => import('../../../tokens/icons/tusd'))
export const tusd_circle_color = lazy.lib(() => import('../../../tokens/icons/tusd_circle_color'))
export const tusd_color = lazy.lib(() => import('../../../tokens/icons/tusd_color'))
export const uni_circle_color = lazy.lib(() => import('../../../tokens/icons/uni_circle_color'))
export const uni_circle_mono = lazy.lib(() => import('../../../tokens/icons/uni_circle_mono'))
export const uni_lp_circle_color = lazy.lib(
  () => import('../../../tokens/icons/uni_lp_circle_color'),
)
export const uni_lp_circle_mono = lazy.lib(() => import('../../../tokens/icons/uni_lp_circle_mono'))
export const unieth = lazy.lib(() => import('../../../tokens/icons/unieth'))
export const univ2_dai_usdc_circles_color = lazy.lib(
  () => import('../../../tokens/icons/univ2_dai_usdc_circles_color'),
)
export const univ2_dai_usdt_circles_color = lazy.lib(
  () => import('../../../tokens/icons/univ2_dai_usdt_circles_color'),
)
export const univ2_eth_usdt_circles_color = lazy.lib(
  () => import('../../../tokens/icons/univ2_eth_usdt_circles_color'),
)
export const univ2_usdc_eth_circles_color = lazy.lib(
  () => import('../../../tokens/icons/univ2_usdc_eth_circles_color'),
)
export const usd_circle_color = lazy.lib(() => import('../../../tokens/icons/usd_circle_color'))
export const usda = lazy.lib(() => import('../../../tokens/icons/usda'))
export const usdc = lazy.lib(() => import('../../../tokens/icons/usdc'))
export const usdc_circle_color = lazy.lib(() => import('../../../tokens/icons/usdc_circle_color'))
export const usde = lazy.lib(() => import('../../../tokens/icons/usde'))
export const usdp_circle_color = lazy.lib(() => import('../../../tokens/icons/usdp_circle_color'))
export const usdt = lazy.lib(() => import('../../../tokens/icons/usdt'))
export const usdt_circle_color = lazy.lib(() => import('../../../tokens/icons/usdt_circle_color'))
export const usdt_color = lazy.lib(() => import('../../../tokens/icons/usdt_color'))
export const wbtc = lazy.lib(() => import('../../../tokens/icons/wbtc'))
export const wbtc_circle_color = lazy.lib(() => import('../../../tokens/icons/wbtc_circle_color'))
export const wbtc_color = lazy.lib(() => import('../../../tokens/icons/wbtc_color'))
export const wbtc_usdc = lazy.lib(() => import('../../../tokens/icons/wbtc_usdc'))
export const weeth_circle_color = lazy.lib(() => import('../../../tokens/icons/weeth_circle_color'))
export const weth_circle_color = lazy.lib(() => import('../../../tokens/icons/weth_circle_color'))
export const wld_circle_color = lazy.lib(() => import('../../../tokens/icons/wld_circle_color'))
export const wsteth_circle_color = lazy.lib(
  () => import('../../../tokens/icons/wsteth_circle_color'),
)
export const wyre = lazy.lib(() => import('../../../tokens/icons/wyre'))
export const xeth = lazy.lib(() => import('../../../tokens/icons/xeth'))
export const yen_circle_color = lazy.lib(() => import('../../../tokens/icons/yen_circle_color'))
export const yfi_circle_color = lazy.lib(() => import('../../../tokens/icons/yfi_circle_color'))
export const yfi_circle_mono = lazy.lib(() => import('../../../tokens/icons/yfi_circle_mono'))
export const yieldbtc_circle_color = lazy.lib(
  () => import('../../../tokens/icons/yieldbtc_circle_color'),
)
export const yieldeth_circle_color = lazy.lib(
  () => import('../../../tokens/icons/yieldeth_circle_color'),
)
export const zerox = lazy.lib(() => import('../../../tokens/icons/zerox'))
export const zerox_circle_color = lazy.lib(() => import('../../../tokens/icons/zerox_circle_color'))
export const zerox_color = lazy.lib(() => import('../../../tokens/icons/zerox_color'))
export const autoBuy = lazy.lib(() => import('../../../tokens/icons/autoBuy'))
export const autoSell = lazy.lib(() => import('../../../tokens/icons/autoSell'))
export const stopLoss = lazy.lib(() => import('../../../tokens/icons/stopLoss'))
export const trailingStopLoss = lazy.lib(() => import('../../../tokens/icons/stopLoss'))
export const takeProfit = lazy.lib(() => import('../../../tokens/icons/takeProfit'))
export const partialTakeProfit = lazy.lib(() => import('../../../tokens/icons/takeProfit'))
export const autoTakeProfit = lazy.lib(() => import('../../../tokens/icons/takeProfit'))
export const constantMultiple = lazy.lib(() => import('../../../tokens/icons/takeProfit')) // doesn't matter, no longer supported
export const rays = lazy.lib(() => import('../../../tokens/icons/rays'))
export const chevron_down = lazy.lib(() => import('../../../tokens/icons/chevron_down'))
export const search_icon = lazy.lib(() => import('../../../tokens/icons/search_icon'))
export const tooltip = lazy.lib(() => import('../../../tokens/icons/tooltip'))
export const checkmark_colorful = lazy.lib(() => import('../../../tokens/icons/checkmark_colorful'))
export const close_colorful = lazy.lib(() => import('../../../tokens/icons/close_colorful'))
