/**
 * @enum CommonTokenSymbols
 * @description Common token symbols to be used with the tokens manager. Tokens can be retrieved by their symbol
 *              using the tokens manager by passing an untyped string. These list is just a convenience utility
 *              to avoid typos when using the tokens manager
 */
export enum CommonTokenSymbols {
  USDT = 'USDT',
  USDC = 'USDC',
  DAI = 'DAI',
  WETH = 'WETH',
  WBTC = 'WBTC',
  ETH = 'ETH',
  wstETH = 'wstETH',
  sDAI = 'sDAI',
  USDA = 'USDA',
  ezETH = 'ezETH',
  osETH = 'osETH',
  weETH = 'weETH',
  USDe = 'USDe',
  sUSDe = 'sUSDe',
  LINK = 'LINK',
  MANA = 'MANA',
  MATIC = 'MATIC',
  MKR = 'MKR',
  UNI = 'UNI',
  YFI = 'YFI',
  stETH = 'stETH',
  GUSD = 'GUSD',
  USDP = 'USDP',
  renBTC = 'renBTC',
  rETH = 'rETH',
  GNO = 'GNO',
  LDO = 'LDO',
  cbETH = 'cbETH',
  RPL = 'RPL',
  LUSD = 'LUSD',
  AAVE = 'AAVE',
  CRV = 'CRV',
  SNX = 'SNX',
  BAL = 'BAL',
  ENS = 'ENS',
  ONEINCH = '1INCH',
  FRAX = 'FRAX',
  GHO = 'GHO',
  STG = 'STG',
  KNC = 'KNC',
  FXS = 'FXS',
  crvUSD = 'crvUSD',
  PYUSD = 'PYUSD',
}
