declare const styles: {
  readonly "backgroundOrb": string;
  readonly "buildBySection": string;
  readonly "card": string;
  readonly "cardContent": string;
  readonly "cardSection": string;
  readonly "cardSubtitle": string;
  readonly "heroBackground": string;
  readonly "heroContent": string;
  readonly "heroParagraph": string;
  readonly "heroWrapper": string;
  readonly "iconBadge": string;
  readonly "iconColumn": string;
  readonly "iconGrid": string;
  readonly "infoGrid": string;
  readonly "introCard": string;
  readonly "introCardParagraph": string;
  readonly "introCardsRow": string;
  readonly "linesBackground": string;
  readonly "linesBackgroundSecondBlock": string;
  readonly "marketLogosGrid": string;
  readonly "sdkDescription": string;
  readonly "sdkSection": string;
  readonly "sdkTextColumn": string;
  readonly "selfManagedVaultScreenshotWrapper": string;
  readonly "subLandingPageSection": string;
  readonly "subSectionTextSecondary": string;
};
export = styles;

