packages:
  - 'packages/**'
  - 'apps/*'
  - 'sdk/**'
  - 'stacks/**'
  - 'turbo/**'
  - 'background-jobs/**'
  - 'summerfi-api/**'
  - 'external-api/**'
  - '!**/test/**'
  - '!**/.sst/**'
  - 'earn-protocol/abis'
