packages:
  - 'packages/**'
  - 'apps/*'
  - 'sdk/**'
  - '!sdk/sdk-client/bundle'
  - '!sdk/sdk-common/bundle'
  - 'stacks/**'
  - 'turbo/**'
  - 'background-jobs/**'
  - 'summerfi-api/**'
  - 'external-api/**'
  - '!**/test/**'
  - '!**/.sst/**'
  - 'armada-protocol/abis'
