export const REVALIDATION_TIMES = {
  // values are seconds
  PORTFOLIO_ASSETS: 60,
  PORTFOLIO_DATA: 300,
  POSITION_HISTORY: 120,
  INTEREST_RATES: 60,
  RAYS_LEADERBOARD: 60,
  SUMR_DELEGATES: 60,
  CONFIG: 60,
  ALWAYS_FRESH: 0,
  MEDIAN_DEFI_YIELD: 3600,
}

export const REVALIDATION_TAGS = {
  PORTFOLIO_ASSETS: 'portfolio-assets',
  POSITION_HISTORY: 'position-history',
  CONFIG: 'config',
}
