export const CACHE_TAGS = {
  VAULTS_LIST: 'vaults-list',
  INTEREST_RATES: 'interest-rates',
  PORTFOLIO_ASSETS: 'portfolio-assets',
  PORTFOLIO_DATA: 'portfolio-data',
  POSITION_HISTORY: 'position-history',
  POSITIONS_ACTIVE_PERIODS: 'positions-active-periods',
  CONFIG: 'config',
  MIGRATION_DATA: 'migration-data',
  PRO_APP_STATS: 'pro-app-stats',
  LP_VAULTS_APY: 'lp-vaults-apy',
  LP_REBALANCE_ACTIVITY: 'lp-rebalance-activity',
  LP_SUMMER_PRO_STATS: 'lp-summer-pro-stats',
  LP_PROTOCOLS_TVL: 'lp-protocols-tvl',
  LP_PROTOCOLS_APY: 'lp-protocols-apy',
  BEACH_CLUB_PROFILE: 'beach-club-profile',
  BEACH_CLUB_RECRUITS: 'beach-club-recruits',
  BLOG_POSTS: 'blog-posts',
  DEFI_PROJECT_YIELD: 'defi-project-yield',
  DEFI_MEDIAN_YIELD: 'defi-median-yield',
  DEFI_PROTOCOL_TVL: 'defi-protocol-tvl',
  USER_DATA: 'user-data',
}

export const CACHE_TIMES = {
  VAULTS_LIST: 300,
  INTEREST_RATES: 600,
  PORTFOLIO_ASSETS: 60,
  PORTFOLIO_DATA: 300,
  POSITION_HISTORY: 120,
  POSITIONS_ACTIVE_PERIODS: 120,
  CONFIG: 60,
  MIGRATION_DATA: 30,
  PRO_APP_STATS: 900,
  LP_VAULTS_APY: 300,
  LP_REBALANCE_ACTIVITY: 300,
  LP_SUMMER_PRO_STATS: 3600,
  LP_PROTOCOLS_TVL: 3600,
  LP_PROTOCOLS_APY: 3600,
  BEACH_CLUB_PROFILE: 300,
  BEACH_CLUB_RECRUITS: 300,
  BLOG_POSTS: 300,
  DEFI_PROJECT_YIELD: 600,
  DEFI_MEDIAN_YIELD: 600,
  DEFI_PROTOCOL_TVL: 600,
  ALWAYS_FRESH: 0,
  USER_DATA: 300,
}
