// WORKAROUND: re-exporting protocol-plugins to give FE access to protocol plugins types
export {
  AaveV3LendingPoolId,
  AaveV3LendingPosition,
  AaveV3LendingPositionId,
  AaveV3Protocol,
  EmodeType,
  isAaveV3LendingPoolId,
  isMakerLendingPoolId,
  isMorphoLendingPoolId,
  isSparkLendingPoolId,
  MakerLendingPoolId,
  MakerLendingPosition,
  MakerLendingPositionId,
  MakerProtocol,
  MorphoLendingPoolId,
  MorphoLendingPosition,
  MorphoLendingPositionId,
  MorphoProtocol,
  SparkLendingPoolId,
  SparkLendingPosition,
  SparkLendingPositionId,
  SparkProtocol,
  type IAaveV3LendingPoolId,
  type IAaveV3Protocol,
  type ILKType,
  type IMakerLendingPoolId,
  type IMakerProtocol,
  type IMorphoLendingPoolId,
  type IMorphoProtocol,
  type ISparkLendingPoolId,
  type ISparkProtocol,
  type MakerLendingPositionIdParameters,
  type MakerLendingPositionParameters,
} from '@summerfi/protocol-plugins'
export { Chain } from './implementation/Chain'
export { ChainsManagerClient } from './implementation/ChainsManager'
export { makeSDK } from './implementation/MakeSDK'
export { PortfolioManager } from './implementation/PortfolioManager'
export { ProtocolsManagerClient } from './implementation/ProtocolsManagerClient'
export { SDKManager } from './implementation/SDKManager'
export { TokensManagerClient } from './implementation/TokensManagerClient'
export { UserClient } from './implementation/UserClient'
export { UsersManager } from './implementation/UsersManager'
export type { IArmadaManagerClient } from './interfaces/ArmadaManager/IArmadaManagerClient'
export type { IChain } from './interfaces/IChain'
export type { IChainsManagerClient } from './interfaces/IChainsManager'
export type { IPortfolioManager } from './interfaces/IPortfolioManager'
export type { IProtocolsManagerClient } from './interfaces/IProtocolsManagerClient'
export type { ISDKManager } from './interfaces/ISDKManager'
export type { ITokensManagerClient } from './interfaces/ITokensManagerClient'
export type { IUserClient } from './interfaces/IUserClient'
export type { IUsersManager } from './interfaces/IUsersManager'
export { PositionUtils } from './utils/PositionUtils'

export {
  Address,
  AddressType,
  ArmadaMigrationType,
  ArmadaOperationType,
  ArmadaPosition,
  ArmadaPositionId,
  ArmadaProtocol,
  ArmadaVault,
  ArmadaVaultId,
  ArmadaVaultInfo,
  ChainIds,
  ChainInfo,
  FiatCurrency,
  FiatCurrencyAmount,
  getChainInfoByChainId,
  isAddress,
  isArmadaMigrationType,
  isArmadaPosition,
  isArmadaPositionId,
  isArmadaProtocol,
  isArmadaVault,
  isArmadaVaultId,
  isArmadaVaultInfo,
  isChainId,
  isChainInfo,
  isDenomination,
  isFiatCurrency,
  isFiatCurrencyAmount,
  isPercentage,
  isPrice,
  isRiskRatio,
  isToken,
  isTokenAmount,
  isTokenSymbol,
  isUser,
  isWallet,
  OracleProviderType,
  Percentage,
  Price,
  RiskRatio,
  SwapProviderType,
  Token,
  TokenAmount,
  TransactionType,
  User,
  Wallet,
  type AddressValue,
  type ApproveTransactionInfo,
  type ArmadaMigratablePosition,
  type ArmadaMigratablePositionApy,
  type BridgeTransactionInfo,
  type ChainId,
  type ClaimTransactionInfo,
  type DelegateTransactionInfo,
  type Denomination,
  type DepositTransactionInfo,
  type IAddress,
  type IArmadaPosition,
  type IArmadaPositionId,
  type IArmadaProtocol,
  type IArmadaVault,
  type IArmadaVaultId,
  type IArmadaVaultInfo,
  type IChainInfo,
  type IFiatCurrencyAmount,
  type IPercentage,
  type IPrice,
  type IRiskRatio,
  type ISpotPriceInfo,
  type ISpotPricesInfo,
  type IToken,
  type ITokenAmount,
  type IUser,
  type IWallet,
  type MigrationTransactionInfo,
  type QuoteData,
  type StakeTransactionInfo,
  type SwapData,
  type TokenSymbol,
  type Transaction,
  type TransactionInfo,
  type TransactionPriceImpact,
  type UnstakeTransactionInfo,
  type VaultSwitchTransactionInfo,
  type WithdrawTransactionInfo,
} from '@summerfi/sdk-common'
