export const aaveStrategiesLite = [
  // used in navigation links, cut down version of the OB list
  {
    network: 'ethereum',
    name: 'stETHethV2',
    urlSlug: 'stETHeth',
    tokens: {
      collateral: 'STETH',
      debt: 'ETH',
      deposit: 'ETH',
    },
    type: 'Earn',
    protocol: 'aavev2',
  },
  {
    network: 'ethereum',
    name: 'ethusdcV2',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev2',
  },
  {
    network: 'ethereum',
    name: 'stETHusdcV2',
    urlSlug: 'stETHusdc',
    tokens: {
      collateral: 'STETH',
      debt: 'USDC',
      deposit: 'STETH',
    },
    type: 'Multiply',
    protocol: 'aavev2',
  },
  {
    network: 'ethereum',
    name: 'wBTCusdcV2',
    urlSlug: 'wBTCusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev2',
  },
  {
    network: 'optimism',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'ethusdc.eV3',
    urlSlug: 'ethusdc.e',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC.E',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcsusdV3',
    urlSlug: 'usdcsusd',
    tokens: {
      collateral: 'USDC',
      debt: 'SUSD',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.esusdV3',
    urlSlug: 'usdc.esusd',
    tokens: {
      collateral: 'USDC.E',
      debt: 'SUSD',
      deposit: 'USDC.E',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethusdcV3',
    urlSlug: 'wstethusdc',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethusdc.eV3',
    urlSlug: 'wstethusdc.e',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC.E',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wbtcusdcV3',
    urlSlug: 'wbtcusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wbtcusdc.eV3',
    urlSlug: 'wbtcusdc.e',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC.E',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'daiethV3',
    urlSlug: 'daieth',
    tokens: {
      collateral: 'DAI',
      debt: 'ETH',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'daiwbtcV3',
    urlSlug: 'daiwbtc',
    tokens: {
      collateral: 'DAI',
      debt: 'WBTC',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.eethV3',
    urlSlug: 'usdc.eeth',
    tokens: {
      collateral: 'USDC.E',
      debt: 'ETH',
      deposit: 'USDC.E',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcethV3',
    urlSlug: 'usdceth',
    tokens: {
      collateral: 'USDC',
      debt: 'ETH',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcwbtcV3',
    urlSlug: 'usdcwbtc',
    tokens: {
      collateral: 'USDC',
      debt: 'WBTC',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.ewbtcV3',
    urlSlug: 'usdc.ewbtc',
    tokens: {
      collateral: 'USDC.E',
      debt: 'WBTC',
      deposit: 'USDC.E',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'ethusdc.eV3',
    urlSlug: 'ethusdc.e',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC.E',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcsusdV3',
    urlSlug: 'usdcsusd',
    tokens: {
      collateral: 'USDC',
      debt: 'SUSD',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.esusdV3',
    urlSlug: 'usdc.esusd',
    tokens: {
      collateral: 'USDC.E',
      debt: 'SUSD',
      deposit: 'USDC.E',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethusdcV3',
    urlSlug: 'wstethusdc',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethusdc.eV3',
    urlSlug: 'wstethusdc.e',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC.E',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wbtcusdcV3',
    urlSlug: 'wbtcusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wbtcusdc.eV3',
    urlSlug: 'wbtcusdc.e',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC.E',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'daiethV3',
    urlSlug: 'daieth',
    tokens: {
      collateral: 'DAI',
      debt: 'ETH',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'daiwbtcV3',
    urlSlug: 'daiwbtc',
    tokens: {
      collateral: 'DAI',
      debt: 'WBTC',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.eethV3',
    urlSlug: 'usdc.eeth',
    tokens: {
      collateral: 'USDC.E',
      debt: 'ETH',
      deposit: 'USDC.E',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcethV3',
    urlSlug: 'usdceth',
    tokens: {
      collateral: 'USDC',
      debt: 'ETH',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcwbtcV3',
    urlSlug: 'usdcwbtc',
    tokens: {
      collateral: 'USDC',
      debt: 'WBTC',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.ewbtcV3',
    urlSlug: 'usdc.ewbtc',
    tokens: {
      collateral: 'USDC.E',
      debt: 'WBTC',
      deposit: 'USDC.E',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdcsusdV3',
    urlSlug: 'usdcsusd',
    tokens: {
      collateral: 'USDC',
      debt: 'SUSD',
      deposit: 'USDC',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'usdc.esusdV3',
    urlSlug: 'usdc.esusd',
    tokens: {
      collateral: 'USDC.E',
      debt: 'SUSD',
      deposit: 'USDC.E',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'optimism',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wstethusdcV3',
    urlSlug: 'wstethusdc',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wbtcusdcV3',
    urlSlug: 'wbtcusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'rethdaiV3',
    urlSlug: 'rethdai',
    tokens: {
      collateral: 'RETH',
      debt: 'DAI',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'rethusdcV3',
    urlSlug: 'rethusdc',
    tokens: {
      collateral: 'RETH',
      debt: 'USDC',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'rethethV3',
    urlSlug: 'retheth',
    tokens: {
      collateral: 'RETH',
      debt: 'ETH',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'weethethV3',
    urlSlug: 'weetheth',
    tokens: {
      collateral: 'WEETH',
      debt: 'ETH',
      deposit: 'WEETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'daiethV3',
    urlSlug: 'daieth',
    tokens: {
      collateral: 'DAI',
      debt: 'ETH',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'daiwbtcV3',
    urlSlug: 'daiwbtc',
    tokens: {
      collateral: 'DAI',
      debt: 'WBTC',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'usdcethV3',
    urlSlug: 'usdceth',
    tokens: {
      collateral: 'USDC',
      debt: 'ETH',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'usdcwbtcV3',
    urlSlug: 'usdcwbtc',
    tokens: {
      collateral: 'USDC',
      debt: 'WBTC',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wstethusdcV3',
    urlSlug: 'wstethusdc',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wbtcusdcV3',
    urlSlug: 'wbtcusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'rethdaiV3',
    urlSlug: 'rethdai',
    tokens: {
      collateral: 'RETH',
      debt: 'DAI',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'rethusdcV3',
    urlSlug: 'rethusdc',
    tokens: {
      collateral: 'RETH',
      debt: 'USDC',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'daiethV3',
    urlSlug: 'daieth',
    tokens: {
      collateral: 'DAI',
      debt: 'ETH',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'daiwbtcV3',
    urlSlug: 'daiwbtc',
    tokens: {
      collateral: 'DAI',
      debt: 'WBTC',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'usdcethV3',
    urlSlug: 'usdceth',
    tokens: {
      collateral: 'USDC',
      debt: 'ETH',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'usdcwbtcV3',
    urlSlug: 'usdcwbtc',
    tokens: {
      collateral: 'USDC',
      debt: 'WBTC',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'rethethV3',
    urlSlug: 'retheth',
    tokens: {
      collateral: 'RETH',
      debt: 'ETH',
      deposit: 'RETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'arbitrum',
    name: 'weethethV3',
    urlSlug: 'weetheth',
    tokens: {
      collateral: 'WEETH',
      debt: 'ETH',
      deposit: 'WEETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethethV3',
    urlSlug: 'cbetheth',
    tokens: {
      collateral: 'CBETH',
      debt: 'ETH',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethusdcV3',
    urlSlug: 'cbethusdc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDC',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethdaiV3',
    urlSlug: 'cbethdai',
    tokens: {
      collateral: 'CBETH',
      debt: 'DAI',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethghoV3',
    urlSlug: 'cbethgho',
    tokens: {
      collateral: 'CBETH',
      debt: 'GHO',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethusdcV3',
    urlSlug: 'cbethusdc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDC',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'daiethV3',
    urlSlug: 'daieth',
    tokens: {
      collateral: 'DAI',
      debt: 'ETH',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'daimkrV3',
    urlSlug: 'daimkr',
    tokens: {
      collateral: 'DAI',
      debt: 'MKR',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'daiwbtcV3',
    urlSlug: 'daiwbtc',
    tokens: {
      collateral: 'DAI',
      debt: 'WBTC',
      deposit: 'DAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ldousdtV3',
    urlSlug: 'ldousdt',
    tokens: {
      collateral: 'LDO',
      debt: 'USDT',
      deposit: 'LDO',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkdaiV3',
    urlSlug: 'linkdai',
    tokens: {
      collateral: 'LINK',
      debt: 'DAI',
      deposit: 'LINK',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkghoV3',
    urlSlug: 'linkgho',
    tokens: {
      collateral: 'LINK',
      debt: 'GHO',
      deposit: 'LINK',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkusdcV3',
    urlSlug: 'linkusdc',
    tokens: {
      collateral: 'LINK',
      debt: 'USDC',
      deposit: 'LINK',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkusdtV3',
    urlSlug: 'linkusdt',
    tokens: {
      collateral: 'LINK',
      debt: 'USDT',
      deposit: 'LINK',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkethV3',
    urlSlug: 'linketh',
    tokens: {
      collateral: 'LINK',
      debt: 'ETH',
      deposit: 'LINK',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'mkrdaiV3',
    urlSlug: 'mkrdai',
    tokens: {
      collateral: 'MKR',
      debt: 'DAI',
      deposit: 'MKR',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethdaiV3',
    urlSlug: 'rethdai',
    tokens: {
      collateral: 'RETH',
      debt: 'DAI',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethghoV3',
    urlSlug: 'rethgho',
    tokens: {
      collateral: 'RETH',
      debt: 'GHO',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethusdtV3',
    urlSlug: 'rethusdt',
    tokens: {
      collateral: 'RETH',
      debt: 'USDT',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethethV3',
    urlSlug: 'retheth',
    tokens: {
      collateral: 'RETH',
      debt: 'ETH',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethusdcV3',
    urlSlug: 'rethusdc',
    tokens: {
      collateral: 'RETH',
      debt: 'USDC',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcethV3',
    urlSlug: 'usdceth',
    tokens: {
      collateral: 'USDC',
      debt: 'ETH',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcwbtcV3',
    urlSlug: 'usdcwbtc',
    tokens: {
      collateral: 'USDC',
      debt: 'WBTC',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcghoV3',
    urlSlug: 'usdcgho',
    tokens: {
      collateral: 'USDC',
      debt: 'GHO',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcwstethV3',
    urlSlug: 'usdcwsteth',
    tokens: {
      collateral: 'USDC',
      debt: 'WSTETH',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdtethV3',
    urlSlug: 'usdteth',
    tokens: {
      collateral: 'USDT',
      debt: 'ETH',
      deposit: 'USDT',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcusdtV3',
    urlSlug: 'usdcusdt',
    tokens: {
      collateral: 'USDC',
      debt: 'USDT',
      deposit: 'USDC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcusdcV3',
    urlSlug: 'wbtcusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcghoV3',
    urlSlug: 'wbtcgho',
    tokens: {
      collateral: 'WBTC',
      debt: 'GHO',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtclusdV3',
    urlSlug: 'wbtclusd',
    tokens: {
      collateral: 'WBTC',
      debt: 'LUSD',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcusdtV3',
    urlSlug: 'wbtcusdt',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDT',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcethV3',
    urlSlug: 'wbtceth',
    tokens: {
      collateral: 'WBTC',
      debt: 'ETH',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethghoV3',
    urlSlug: 'ethgho',
    tokens: {
      collateral: 'ETH',
      debt: 'GHO',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethusdtV3',
    urlSlug: 'ethusdt',
    tokens: {
      collateral: 'ETH',
      debt: 'USDT',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethwbtcV3',
    urlSlug: 'ethwbtc',
    tokens: {
      collateral: 'ETH',
      debt: 'WBTC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethcbethV3',
    urlSlug: 'wstethcbeth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'CBETH',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethghoV3',
    urlSlug: 'wstethgho',
    tokens: {
      collateral: 'WSTETH',
      debt: 'GHO',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethlusdV3',
    urlSlug: 'wstethlusd',
    tokens: {
      collateral: 'WSTETH',
      debt: 'LUSD',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethrplV3',
    urlSlug: 'wstethrpl',
    tokens: {
      collateral: 'WSTETH',
      debt: 'RPL',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'weethethV3',
    urlSlug: 'weetheth',
    tokens: {
      collateral: 'WEETH',
      debt: 'ETH',
      deposit: 'WEETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethusdcV3',
    urlSlug: 'wstethusdc',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaighoV3',
    urlSlug: 'sdaigho',
    tokens: {
      collateral: 'SDAI',
      debt: 'GHO',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdtV3',
    urlSlug: 'sdaiusdt',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDT',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiwbtcV3',
    urlSlug: 'sdaiwbtc',
    tokens: {
      collateral: 'SDAI',
      debt: 'WBTC',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiethV3',
    urlSlug: 'sdaieth',
    tokens: {
      collateral: 'SDAI',
      debt: 'ETH',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdcV3',
    urlSlug: 'sdaiusdc',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDC',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdailusdV3',
    urlSlug: 'sdailusd',
    tokens: {
      collateral: 'SDAI',
      debt: 'LUSD',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaifraxV3',
    urlSlug: 'sdaifrax',
    tokens: {
      collateral: 'SDAI',
      debt: 'FRAX',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaidaiV3',
    urlSlug: 'sdaidai',
    tokens: {
      collateral: 'SDAI',
      debt: 'DAI',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethusdtV3',
    urlSlug: 'wstethusdt',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDT',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethethV3',
    urlSlug: 'cbetheth',
    tokens: {
      collateral: 'CBETH',
      debt: 'ETH',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethusdcV3',
    urlSlug: 'cbethusdc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDC',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethdaiV3',
    urlSlug: 'cbethdai',
    tokens: {
      collateral: 'CBETH',
      debt: 'DAI',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethghoV3',
    urlSlug: 'cbethgho',
    tokens: {
      collateral: 'CBETH',
      debt: 'GHO',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethusdcV3',
    urlSlug: 'cbethusdc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDC',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'daiethV3',
    urlSlug: 'daieth',
    tokens: {
      collateral: 'DAI',
      debt: 'ETH',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'daimkrV3',
    urlSlug: 'daimkr',
    tokens: {
      collateral: 'DAI',
      debt: 'MKR',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'daiwbtcV3',
    urlSlug: 'daiwbtc',
    tokens: {
      collateral: 'DAI',
      debt: 'WBTC',
      deposit: 'DAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ldousdtV3',
    urlSlug: 'ldousdt',
    tokens: {
      collateral: 'LDO',
      debt: 'USDT',
      deposit: 'LDO',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkdaiV3',
    urlSlug: 'linkdai',
    tokens: {
      collateral: 'LINK',
      debt: 'DAI',
      deposit: 'LINK',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkghoV3',
    urlSlug: 'linkgho',
    tokens: {
      collateral: 'LINK',
      debt: 'GHO',
      deposit: 'LINK',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkusdcV3',
    urlSlug: 'linkusdc',
    tokens: {
      collateral: 'LINK',
      debt: 'USDC',
      deposit: 'LINK',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkusdtV3',
    urlSlug: 'linkusdt',
    tokens: {
      collateral: 'LINK',
      debt: 'USDT',
      deposit: 'LINK',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'linkethV3',
    urlSlug: 'linketh',
    tokens: {
      collateral: 'LINK',
      debt: 'ETH',
      deposit: 'LINK',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'mkrdaiV3',
    urlSlug: 'mkrdai',
    tokens: {
      collateral: 'MKR',
      debt: 'DAI',
      deposit: 'MKR',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethdaiV3',
    urlSlug: 'rethdai',
    tokens: {
      collateral: 'RETH',
      debt: 'DAI',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethghoV3',
    urlSlug: 'rethgho',
    tokens: {
      collateral: 'RETH',
      debt: 'GHO',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethusdtV3',
    urlSlug: 'rethusdt',
    tokens: {
      collateral: 'RETH',
      debt: 'USDT',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethusdcV3',
    urlSlug: 'rethusdc',
    tokens: {
      collateral: 'RETH',
      debt: 'USDC',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcethV3',
    urlSlug: 'usdceth',
    tokens: {
      collateral: 'USDC',
      debt: 'ETH',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcwbtcV3',
    urlSlug: 'usdcwbtc',
    tokens: {
      collateral: 'USDC',
      debt: 'WBTC',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcghoV3',
    urlSlug: 'usdcgho',
    tokens: {
      collateral: 'USDC',
      debt: 'GHO',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcwstethV3',
    urlSlug: 'usdcwsteth',
    tokens: {
      collateral: 'USDC',
      debt: 'WSTETH',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdtethV3',
    urlSlug: 'usdteth',
    tokens: {
      collateral: 'USDT',
      debt: 'ETH',
      deposit: 'USDT',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcusdtV3',
    urlSlug: 'usdcusdt',
    tokens: {
      collateral: 'USDC',
      debt: 'USDT',
      deposit: 'USDC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcusdcV3',
    urlSlug: 'wbtcusdc',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDC',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcghoV3',
    urlSlug: 'wbtcgho',
    tokens: {
      collateral: 'WBTC',
      debt: 'GHO',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtclusdV3',
    urlSlug: 'wbtclusd',
    tokens: {
      collateral: 'WBTC',
      debt: 'LUSD',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcusdtV3',
    urlSlug: 'wbtcusdt',
    tokens: {
      collateral: 'WBTC',
      debt: 'USDT',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wbtcethV3',
    urlSlug: 'wbtceth',
    tokens: {
      collateral: 'WBTC',
      debt: 'ETH',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethghoV3',
    urlSlug: 'ethgho',
    tokens: {
      collateral: 'ETH',
      debt: 'GHO',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethusdtV3',
    urlSlug: 'ethusdt',
    tokens: {
      collateral: 'ETH',
      debt: 'USDT',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'ethwbtcV3',
    urlSlug: 'ethwbtc',
    tokens: {
      collateral: 'ETH',
      debt: 'WBTC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethcbethV3',
    urlSlug: 'wstethcbeth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'CBETH',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethghoV3',
    urlSlug: 'wstethgho',
    tokens: {
      collateral: 'WSTETH',
      debt: 'GHO',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethlusdV3',
    urlSlug: 'wstethlusd',
    tokens: {
      collateral: 'WSTETH',
      debt: 'LUSD',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethrplV3',
    urlSlug: 'wstethrpl',
    tokens: {
      collateral: 'WSTETH',
      debt: 'RPL',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethusdcV3',
    urlSlug: 'wstethusdc',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDC',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaighoV3',
    urlSlug: 'sdaigho',
    tokens: {
      collateral: 'SDAI',
      debt: 'GHO',
      deposit: 'SDAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdtV3',
    urlSlug: 'sdaiusdt',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDT',
      deposit: 'SDAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiwbtcV3',
    urlSlug: 'sdaiwbtc',
    tokens: {
      collateral: 'SDAI',
      debt: 'WBTC',
      deposit: 'SDAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiethV3',
    urlSlug: 'sdaieth',
    tokens: {
      collateral: 'SDAI',
      debt: 'ETH',
      deposit: 'SDAI',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethusdtV3',
    urlSlug: 'wstethusdt',
    tokens: {
      collateral: 'WSTETH',
      debt: 'USDT',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaighoV3',
    urlSlug: 'sdaigho',
    tokens: {
      collateral: 'SDAI',
      debt: 'GHO',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdtV3',
    urlSlug: 'sdaiusdt',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDT',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdcV3',
    urlSlug: 'sdaiusdc',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDC',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdailusdV3',
    urlSlug: 'sdailusd',
    tokens: {
      collateral: 'SDAI',
      debt: 'LUSD',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaifraxV3',
    urlSlug: 'sdaifrax',
    tokens: {
      collateral: 'SDAI',
      debt: 'FRAX',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'sdaidaiV3',
    urlSlug: 'sdaidai',
    tokens: {
      collateral: 'SDAI',
      debt: 'DAI',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstETHethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'ETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'rethethV3',
    urlSlug: 'retheth',
    tokens: {
      collateral: 'RETH',
      debt: 'ETH',
      deposit: 'RETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcusdtV3',
    urlSlug: 'usdcusdt',
    tokens: {
      collateral: 'USDC',
      debt: 'USDT',
      deposit: 'USDC',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethcbethV3',
    urlSlug: 'wstethcbeth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'CBETH',
      deposit: 'CBETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'usdcghoV3',
    urlSlug: 'usdcgho',
    tokens: {
      collateral: 'USDC',
      debt: 'GHO',
      deposit: 'GHO',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'cbethethV3',
    urlSlug: 'cbetheth',
    tokens: {
      collateral: 'CBETH',
      debt: 'ETH',
      deposit: 'CBETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'weethethV3',
    urlSlug: 'weetheth',
    tokens: {
      collateral: 'WEETH',
      debt: 'ETH',
      deposit: 'WEETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'ethereum',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'rethdaiV3',
    urlSlug: 'rethdai',
    tokens: {
      collateral: 'RETH',
      debt: 'DAI',
      deposit: 'RETH',
    },
    type: 'Borrow',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'sdaiethV3',
    urlSlug: 'sdaieth',
    tokens: {
      collateral: 'SDAI',
      debt: 'ETH',
      deposit: 'SDAI',
    },
    type: 'Borrow',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Borrow',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'wstethdaiV3',
    urlSlug: 'wstethdai',
    tokens: {
      collateral: 'WSTETH',
      debt: 'DAI',
      deposit: 'WSTETH',
    },
    type: 'Multiply',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'rethdaiV3',
    urlSlug: 'rethdai',
    tokens: {
      collateral: 'RETH',
      debt: 'DAI',
      deposit: 'RETH',
    },
    type: 'Multiply',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'ethdaiV3',
    urlSlug: 'ethdai',
    tokens: {
      collateral: 'ETH',
      debt: 'DAI',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'sdaiethV3',
    urlSlug: 'sdaieth',
    tokens: {
      collateral: 'SDAI',
      debt: 'ETH',
      deposit: 'SDAI',
    },
    type: 'Multiply',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'wbtcdaiV3',
    urlSlug: 'wbtcdai',
    tokens: {
      collateral: 'WBTC',
      debt: 'DAI',
      deposit: 'WBTC',
    },
    type: 'Multiply',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Earn',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'rethethV3',
    urlSlug: 'retheth',
    tokens: {
      collateral: 'RETH',
      debt: 'ETH',
      deposit: 'RETH',
    },
    type: 'Earn',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdcV3',
    urlSlug: 'sdaiusdc',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDC',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'sparkv3',
  },
  {
    network: 'ethereum',
    name: 'sdaiusdtV3',
    urlSlug: 'sdaiusdt',
    tokens: {
      collateral: 'SDAI',
      debt: 'USDT',
      deposit: 'SDAI',
    },
    type: 'Earn',
    protocol: 'sparkv3',
  },
  {
    network: 'base',
    name: 'cbethusdbcV3',
    urlSlug: 'cbethusdbc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDBC',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'cbethusdcV3',
    urlSlug: 'cbethusdc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDC',
      deposit: 'CBETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'ethusdbcV3',
    urlSlug: 'ethusdbc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDBC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Borrow',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'cbethusdbcV3',
    urlSlug: 'cbethusdbc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDBC',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'cbethusdcV3',
    urlSlug: 'cbethusdc',
    tokens: {
      collateral: 'CBETH',
      debt: 'USDC',
      deposit: 'CBETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'ethusdbcV3',
    urlSlug: 'ethusdbc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDBC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'ethusdcV3',
    urlSlug: 'ethusdc',
    tokens: {
      collateral: 'ETH',
      debt: 'USDC',
      deposit: 'ETH',
    },
    type: 'Multiply',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'wstethethV3',
    urlSlug: 'wstetheth',
    tokens: {
      collateral: 'WSTETH',
      debt: 'ETH',
      deposit: 'WSTETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
  {
    network: 'base',
    name: 'cbethethV3',
    urlSlug: 'cbetheth',
    tokens: {
      collateral: 'CBETH',
      debt: 'ETH',
      deposit: 'CBETH',
    },
    type: 'Earn',
    protocol: 'aavev3',
  },
]
