declare const styles: {
  readonly "factsSectionText": string;
  readonly "faqSection": string;
  readonly "governanceSectionDescription": string;
  readonly "governanceSectionText": string;
  readonly "innerHeader": string;
  readonly "leftBlock": string;
  readonly "leftBlockButtons": string;
  readonly "newsListHeader": string;
  readonly "newsListItem": string;
  readonly "newsListItemDescription": string;
  readonly "newsListItemTitle": string;
  readonly "newsListItems": string;
  readonly "newsListWrapper": string;
  readonly "rightBlock": string;
  readonly "rightBlockBottomBorder": string;
  readonly "rightBlockCountdown": string;
  readonly "rightBlockSumrLogo": string;
  readonly "rightBlockYieldSources": string;
  readonly "sectionCardWrapper": string;
  readonly "twoColumnHeader": string;
  readonly "twoColumnHeaderBlock": string;
  readonly "understandingSumr": string;
  readonly "understandingSumrText": string;
  readonly "waysToAccessSumrSection": string;
  readonly "wrapper": string;
  readonly "yieldSourceColumn": string;
};
export = styles;

