declare const styles: {
  readonly "backgroundOrb": string;
  readonly "card": string;
  readonly "cardContent": string;
  readonly "cardSection": string;
  readonly "cardSubtitle": string;
  readonly "custodyChecks": string;
  readonly "custodyColumn": string;
  readonly "custodyColumns": string;
  readonly "custodyDescription": string;
  readonly "custodyLogo": string;
  readonly "custodyLogoWrapper": string;
  readonly "custodySection": string;
  readonly "custodySectionLabel": string;
  readonly "heroBackground": string;
  readonly "heroContent": string;
  readonly "heroParagraph": string;
  readonly "heroWrapper": string;
  readonly "icon": string;
  readonly "iconBadge": string;
  readonly "iconColumn": string;
  readonly "linesBackground": string;
  readonly "linesBackgroundSecondBlock": string;
  readonly "partnerLogo": string;
  readonly "partnerLogoFrame": string;
  readonly "partnerLogos": string;
  readonly "subLandingPageSection": string;
  readonly "subSectionColumn": string;
  readonly "subSectionRow": string;
  readonly "subSectionTextSecondary": string;
};
export = styles;

