/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SdkApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "SdkBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SdkRouter": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}