name: Setup VPN
description: Setup VPN
runs:
  - name: Establish VPN connection
    run: |
      sudo apt update
      sudo apt install -y openvpn openvpn-systemd-resolved
      echo 'Configuring the VPN...'
      echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
      echo "${{ secrets.VPN_USERNAME }}" > vpn-credentials.txt
      echo "${{ secrets.VPN_PASSWORD }}" >> vpn-credentials.txt
      echo 'Connecting to the VPN...'
      sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
      sleep 5

  - name: Check VPN connection
    env:
      BORROW_DB_READ_DB: ${{ secrets.BORROW_DB_READ_DB }}
      BORROW_DB_READ_HOST: ${{ secrets.BORROW_DB_READ_HOST }}
      BORROW_DB_READ_USER: ${{ secrets.BORROW_DB_READ_USER }}
      BORROW_DB_READ_PASSWORD: ${{ secrets.BORROW_DB_READ_PASSWORD }}
      PGCONNECT_TIMEOUT: 5
    run: |
      echo 'Checking the VPN connection...'
      sudo systemctl start postgresql.service
      PGPASSWORD=$BORROW_DB_READ_PASSWORD /usr/bin/psql -d $BORROW_DB_READ_DB -U $BORROW_DB_READ_USER -h $BORROW_DB_READ_HOST -c 'SELECT 1;' > /dev/null
      STATUS_CODE=$?
      if ! [[ "$STATUS_CODE" = 0 ]]; then
        echo 'VPN connection failed'
        exit 1
      fi
      echo 'VPN connected!'
