name: Setup workflow
description: Setup workflow
runs:
  - name: Set up turbo cache
    uses: rharkor/caching-for-turbo@v1.5

  - uses: pnpm/action-setup@v2.0.1
    with:
      version: 8.14.1

  - name: Setup Node.js environment
    uses: actions/setup-node@v3
    with:
      node-version: 20
      cache: 'pnpm'
