// Autogenerated by the deployments script
import remoteMainnetStandard from "./deployments/mainnet/remote.Mainnet.standard.json";

export const Deployments = {
    "Mainnet.standard": remoteMainnetStandard
};
