// Autogenerated by the deployments script
import remoteMainnetStandard from "./deployments/mainnet/remote.Mainnet.standard.json";
import remoteBaseStandard from "./deployments/base/remote.Base.standard.json";

export const Deployments = {
    "Mainnet.standard": remoteMainnetStandard,
    "Base.standard": remoteBaseStandard,
};
