// Autogenerated by the deployments script
import hardhatLocalhostStandard from "./deployments/hardhat/hardhat.localhost.standard.json";

export const Deployments = {
  "localhost.standard": hardhatLocalhostStandard,
};
