// Autogenerated by the deployments script
import hardhatHardhatTest from './deployments/hardhat/hardhat.hardhat.test.json'
import hardhatLocalhostStandard from './deployments/hardhat/hardhat.localhost.standard.json'

export const Deployments = {
  'hardhat.test': hardhatHardhatTest,
  'localhost.standard': hardhatLocalhostStandard,
}
