query GetVaults($institutionId: String!) {
  vaults(where: { institution: $institutionId }) {
    protocol {
      network
    }
    id
    name
    rewardTokens {
      id
      token {
        id
        symbol
        decimals
      }
    }
    rewardTokenEmissionsAmount
    rewardTokenEmissionsFinish
    rewardTokenEmissionsUSD
    rebalanceCount
    pricePerShare
    arks {
      id
      productId
      name
      details
      depositLimit
      depositCap
      cumulativeEarnings
      inputTokenBalance
      maxDepositPercentageOfTVL
      inputToken {
        id
        name
        symbol
        decimals
      }
      createdTimestamp
      lastUpdateTimestamp
    }
    inputToken {
      id
      name
      symbol
      decimals
    }
    outputToken {
      id
      name
      symbol
      decimals
    }
    outputTokenSupply
    inputTokenBalance
    inputTokenPriceUSD
    outputTokenPriceUSD
    depositLimit
    depositCap
    minimumBufferBalance
    createdTimestamp
    totalValueLockedUSD
    cumulativeTotalRevenueUSD
    cumulativeSupplySideRevenueUSD
    cumulativeProtocolSideRevenueUSD
    lastUpdateTimestamp
    withdrawableTotalAssets
    withdrawableTotalAssetsUSD
  }
  roundsVaultPair {
    id
    active
    inputVault {
      id
      currentRound
      minPositionSize
      underlyingToken {
        id
        name
        symbol
        decimals
      }
      exchangeAssetToken {
        id
        name
        symbol
        decimals
      }
    }
    outputVault {
      id
      currentRound
      minPositionSize
      underlyingToken {
        id
        name
        symbol
        decimals
      }
      exchangeAssetToken {
        id
        name
        symbol
        decimals
      }
    }
  }
}
query GetVault($id: ID!) {
  vault(id: $id) {
    protocol {
      network
    }
    id
    name
    rewardTokens {
      id
      token {
        id
        symbol
        decimals
      }
    }
    rewardTokenEmissionsAmount
    rewardTokenEmissionsFinish
    rewardTokenEmissionsUSD
    rebalanceCount
    pricePerShare
    arks {
      id
      productId
      name
      details
      depositLimit
      depositCap
      cumulativeEarnings
      inputTokenBalance
      maxDepositPercentageOfTVL
      inputToken {
        id
        name
        symbol
        decimals
      }
      createdTimestamp
      lastUpdateTimestamp
    }
    inputToken {
      id
      name
      symbol
      decimals
    }
    outputToken {
      id
      name
      symbol
      decimals
    }
    outputTokenSupply
    inputTokenBalance
    inputTokenPriceUSD
    outputTokenPriceUSD
    depositLimit
    depositCap
    minimumBufferBalance
    createdTimestamp
    totalValueLockedUSD
    cumulativeTotalRevenueUSD
    cumulativeSupplySideRevenueUSD
    cumulativeProtocolSideRevenueUSD
    lastUpdateTimestamp
    withdrawableTotalAssets
    withdrawableTotalAssetsUSD
    isWhitelistOpen
    roundsVaultPair {
      id
      active
      inputVault {
        id
        currentRound
        minPositionSize
        underlyingToken {
          id
          name
          symbol
          decimals
        }
        exchangeAssetToken {
          id
          name
          symbol
          decimals
        }
      }
      outputVault {
        id
        currentRound
        minPositionSize
        underlyingToken {
          id
          name
          symbol
          decimals
        }
        exchangeAssetToken {
          id
          name
          symbol
          decimals
        }
      }
    }
  }
}
query GetRwaReceipts($account: String!, $vault: String!) {
  receipts(where: { account: $account, vault: $vault, balance_gt: "0" }) {
    id
    balance
    round {
      roundId
      state
    }
    vault {
      id
    }
  }
}
