export const ContractsVersionsDefaultName = 'contracts-versions'
export const SnapshotDirectory = 'versions'
export const SnapshotTrailingTag = 'snapshot'
export const SnapshotTagDelimiter = '.'
export const SnapshotNameExtension = 'json'
