import { FunctionComponent, LazyExoticComponent, SVGProps } from 'react'

export type IconExportType = LazyExoticComponent<
  FunctionComponent<
    SVGProps<SVGSVGElement> & {
      title?: string
    }
  >
>

export declare const IconsList: {
  aave_cbETH_usdc: IconExportType
  aave_circle_color: IconExportType
  aave_eth_usdc: IconExportType
  aave_steth_eth: IconExportType
  aave_steth_usdc: IconExportType
  aave_wbtc_usdc: IconExportType
  aero: IconExportType
  ajna_circle_color: IconExportType
  apxeth_circle_color: IconExportType
  arb_circle: IconExportType
  arb: IconExportType
  arrow_backward: IconExportType
  arrow_decrease: IconExportType
  arrow_forward: IconExportType
  arrow_forward_colorful: IconExportType
  arrow_increase: IconExportType
  augur_circle_color: IconExportType
  augur_color: IconExportType
  augur: IconExportType
  autoBuy: IconExportType
  autoSell: IconExportType
  autoTakeProfit: IconExportType
  bal_circle_color: IconExportType
  bal_circle: IconExportType
  bal: IconExportType
  base: IconExportType
  base_circle: IconExportType
  bat_circle_color: IconExportType
  bat_color: IconExportType
  bat: IconExportType
  beach_club_icon: IconExportType
  beach_club_rewards: IconExportType
  bridge: IconExportType
  big_certificate: IconExportType
  big_press: IconExportType
  big_pot: IconExportType
  big_reload: IconExportType
  bsdeth_circle_color: IconExportType
  btc_circle_color: IconExportType
  btc_circle_mono: IconExportType
  bug: IconExportType
  cbeth_circle_color: IconExportType
  cbeth_eth: IconExportType
  cbeth_usdc: IconExportType
  cbbtc_circle_color: IconExportType
  chai_circle_color: IconExportType
  chai_color: IconExportType
  chai: IconExportType
  chain_security: IconExportType
  chainlink_circle_color: IconExportType
  chainlink_color: IconExportType
  chainlink: IconExportType
  checkmark_colorful: IconExportType
  checkmark_colorful_beach_club: IconExportType
  checkmark_circle: IconExportType
  checkmark_colorful_circle: IconExportType
  checkmark_colorful_slim: IconExportType
  checkmark: IconExportType
  chevron_down: IconExportType
  chevron_left: IconExportType
  chevron_right: IconExportType
  chevron_up: IconExportType
  clock: IconExportType
  close_colorful: IconExportType
  close_squared: IconExportType
  close: IconExportType
  cog: IconExportType
  compound_circle_color: IconExportType
  compound_color: IconExportType
  compound: IconExportType
  constantMultiple: IconExportType
  crv_circle: IconExportType
  colorful_hamburger: IconExportType
  colorful_arrow: IconExportType
  crv: IconExportType
  cseth: IconExportType
  cut: IconExportType
  dai_circle_color: IconExportType
  dai_color: IconExportType
  dai: IconExportType
  degen: IconExportType
  deposit: IconExportType
  deth: IconExportType
  digix_circle_color: IconExportType
  discord: IconExportType
  down_up: IconExportType
  dot_arrow_right_colorful: IconExportType
  earn_network_all: IconExportType
  earn_network_arbitrum: IconExportType
  earn_network_base: IconExportType
  earn_network_blast: IconExportType
  earn_network_ethereum: IconExportType
  earn_network_hyperliquid: IconExportType
  earn_network_optimism: IconExportType
  earn_network_sonic: IconExportType
  earn_institution: IconExportType
  edit: IconExportType
  ena: IconExportType
  eth_circle_color: IconExportType
  eth_circle_mono: IconExportType
  eth_usdc: IconExportType
  ether_circle_color: IconExportType
  ether_color: IconExportType
  ether: IconExportType
  eurc: IconExportType
  euler: IconExportType
  euro_circle_color: IconExportType
  exchange: IconExportType
  eye: IconExportType
  ezeth: IconExportType
  etherscan: IconExportType
  frax_circle_color: IconExportType
  gemini_circle_color: IconExportType
  gamepad: IconExportType
  gemini_color: IconExportType
  gemini: IconExportType
  gho_circle_color: IconExportType
  gno_circle_color: IconExportType
  golem_circle_color: IconExportType
  guniv3_dai_usdc1_circles_color: IconExportType
  gusd_circle_color: IconExportType
  gusd_circle_mono: IconExportType
  info: IconExportType
  info_colorful: IconExportType
  knc_circle_color: IconExportType
  kyber_circle_color: IconExportType
  kyber_color: IconExportType
  kyber: IconExportType
  kyc_colorful: IconExportType
  latamex: IconExportType
  landing_page_bridge: IconExportType
  landing_page_buy: IconExportType
  landing_page_cashout: IconExportType
  landing_page_send: IconExportType
  landing_page_swap: IconExportType
  layerzero: IconExportType
  lbtc: IconExportType
  ldo_circle: IconExportType
  ldo: IconExportType
  light_bulb: IconExportType
  lightning_colorful: IconExportType
  link_circle_color: IconExportType
  link_circle_mono: IconExportType
  link: IconExportType
  lock: IconExportType
  lock_open_beach_colorful: IconExportType
  lock_open: IconExportType
  lock_beach_colorful: IconExportType
  lrc_circle_color: IconExportType
  lrc_color: IconExportType
  lrc: IconExportType
  lusd_circle_color: IconExportType
  maker_circle_color: IconExportType
  maker_color: IconExportType
  maker: IconExportType
  mana_circle_color: IconExportType
  mana_circle_mono: IconExportType
  mana_color: IconExportType
  mana: IconExportType
  maple: IconExportType
  matic_circle_color: IconExportType
  matic_circle_mono: IconExportType
  mbasis: IconExportType
  menu: IconExportType
  meveth: IconExportType
  mkr_circle_color: IconExportType
  moonpay: IconExportType
  moonwell: IconExportType
  morpho_circle_color: IconExportType
  mpeth: IconExportType
  network_arbitrum: IconExportType
  network_base: IconExportType
  network_ethereum: IconExportType
  network_optimism: IconExportType
  not_supported_icon: IconExportType
  omisego_circle_color: IconExportType
  omisego_color: IconExportType
  omisego: IconExportType
  op_circle: IconExportType
  op: IconExportType
  open_in_new_tab: IconExportType
  oseth_circle_color: IconExportType
  origin: IconExportType
  partialTakeProfit: IconExportType
  pax_circle_color: IconExportType
  pax_color: IconExportType
  pax: IconExportType
  pendle: IconExportType
  person: IconExportType
  play: IconExportType
  plus: IconExportType
  prime: IconExportType
  pyusd: IconExportType
  quant_stamp: IconExportType
  question_mark: IconExportType
  question_o: IconExportType
  question: IconExportType
  radio_button_checked: IconExportType
  radio_button: IconExportType
  rays: IconExportType
  rbn_circle_color: IconExportType
  rebalancing: IconExportType
  refresh: IconExportType
  renbtc_circle_color: IconExportType
  reth_circle_color: IconExportType
  reth_eth: IconExportType
  reth_usdc: IconExportType
  rpl_circle: IconExportType
  rpl: IconExportType
  rseth: IconExportType
  rsweth: IconExportType
  safe: IconExportType
  sai_circle_color: IconExportType
  sai_color: IconExportType
  sai: IconExportType
  sdai_circle_color: IconExportType
  search_icon: IconExportType
  send: IconExportType
  share: IconExportType
  sign_out: IconExportType
  silo: IconExportType
  sky: IconExportType
  snx: IconExportType
  social_link: IconExportType
  social_x: IconExportType
  social_x_beach_club: IconExportType
  social_link_beach_club: IconExportType
  social_question_beach_club: IconExportType
  social_plant_beach_club: IconExportType
  sonic_badge_mainnet: IconExportType
  spark_circle_color: IconExportType
  stars: IconExportType
  stars_colorful: IconExportType
  star_solid_beach_club: IconExportType
  steth_circle_color: IconExportType
  steth_eth: IconExportType
  steth_usdc: IconExportType
  stopLoss: IconExportType
  styeth_circle_color: IconExportType
  sumr: IconExportType
  summer_light: IconExportType
  summer_illustration_check: IconExportType
  summer_illustration_email: IconExportType
  summer_illustration_failed: IconExportType
  summer_illustration_gas_fee: IconExportType
  summer_illustration_identity: IconExportType
  summer_illustration_logo: IconExportType
  summer_illustration_passkey: IconExportType
  summer_illustration_shield: IconExportType
  summer_illustration_switch: IconExportType
  summer_illustration_transak_logo: IconExportType
  summer_illustration_verification: IconExportType
  susd_circle: IconExportType
  susd: IconExportType
  susde: IconExportType
  susds: IconExportType
  swbtc: IconExportType
  syrupusdc: IconExportType
  takeProfit: IconExportType
  tbtc_circle_color: IconExportType
  term: IconExportType
  team_linkedin: IconExportType
  team_x: IconExportType
  tooltip: IconExportType
  trail_of_bits: IconExportType
  trailingStopLoss: IconExportType
  trash: IconExportType
  tusd_circle_color: IconExportType
  tusd_color: IconExportType
  tusd: IconExportType
  uni_circle_color: IconExportType
  uni_circle_mono: IconExportType
  uni_lp_circle_color: IconExportType
  uni_lp_circle_mono: IconExportType
  unieth: IconExportType
  univ2_dai_usdc_circles_color: IconExportType
  univ2_dai_usdt_circles_color: IconExportType
  univ2_eth_usdt_circles_color: IconExportType
  univ2_usdc_eth_circles_color: IconExportType
  usd_circle: IconExportType
  usd_circle_color: IconExportType
  usda: IconExportType
  usdc_circle_color: IconExportType
  usdc: IconExportType
  usde: IconExportType
  usdp_circle_color: IconExportType
  usds: IconExportType
  usdt_circle_color: IconExportType
  usdt_color: IconExportType
  usdt: IconExportType
  'usd₮0_circle_color': IconExportType
  usd0: IconExportType
  'usd0++': IconExportType
  user: IconExportType
  users_beach_club: IconExportType
  vault_network_warning: IconExportType
  wallet: IconExportType
  wbtc_circle_color: IconExportType
  wbtc_color: IconExportType
  wbtc_usdc: IconExportType
  wbtc: IconExportType
  weeth_circle_color: IconExportType
  weth_circle_color: IconExportType
  withdraw: IconExportType
  wld_circle_color: IconExportType
  woeth: IconExportType
  wsteth_circle_color: IconExportType
  wsuperoethb: IconExportType
  wyre: IconExportType
  xeth: IconExportType
  yen_circle_color: IconExportType
  yfi_circle_color: IconExportType
  yfi_circle_mono: IconExportType
  yieldbtc_circle_color: IconExportType
  yieldeth_circle_color: IconExportType
  zerox_circle_color: IconExportType
  zerox_color: IconExportType
  zerox: IconExportType
  wusdl: IconExportType
  plant_colorful: IconExportType
  checkmark_cookie_colorful: IconExportType
  migrate_colorful: IconExportType
  referer_colorful: IconExportType
  x_colorful: IconExportType
  stack_colorful: IconExportType
  fluid: IconExportType
  gearbox: IconExportType
  linkedin: IconExportType
  x: IconExportType
  warning: IconExportType
  scroller_aave: IconExportType
  scroller_sky: IconExportType
  scroller_spark: IconExportType
  scroller_pendle: IconExportType
  scroller_gearbox: IconExportType
  scroller_euler: IconExportType
  scroller_compound: IconExportType
  scroller_ethena: IconExportType
  scroller_fluid: IconExportType
  scroller_morpho: IconExportType
  earn_1_on_1: IconExportType
  earn_discord: IconExportType
  earn_email: IconExportType
  earn_rebalance_activities: IconExportType
  earn_user_activities: IconExportType
  earn_yield_trend: IconExportType
  brand_icon_discord: IconExportType
  brand_icon_github: IconExportType
  brand_icon_twitter: IconExportType
  tabler_x: IconExportType
  tools_kitchen_off: IconExportType
  tools_kitchen: IconExportType
  device_floppy: IconExportType
  trophy: IconExportType
}
