import { type TokenConfig } from '@summerfi/app-types'

export const tokenConfigs: TokenConfig[] = [
  {
    symbol: 'USDP',
    name: 'Pax Dollar',
    iconName: 'usdp_circle_color',
  },
  {
    symbol: 'STETH',
    name: 'Lido Staked ETH',
    iconName: 'aave_cbETH_usdc',
    rootToken: 'ETH',
  },
  {
    symbol: 'MKR',
    name: 'Maker',
    iconName: 'mkr_circle_color',
  },
  {
    symbol: 'WETH',
    name: 'Wrapped Ether',
    iconName: 'weth_circle_color',
  },
  {
    symbol: 'ETH',
    name: 'Ether',
    iconName: 'ether_circle_color',
  },
  {
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin',
    iconName: 'wbtc_circle_color',
    rootToken: 'BTC',
  },
  {
    symbol: 'MANA',
    name: 'Decentraland',
    iconName: 'mana_circle_color',
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    iconName: 'chainlink_circle_color',
  },
  {
    symbol: 'GUSD',
    name: 'Gemini dollar',
    iconName: 'gemini_circle_color',
  },
  {
    symbol: 'YFI',
    name: 'Yearn',
    iconName: 'yfi_circle_color',
  },
  {
    symbol: 'MATIC',
    name: 'MATIC',
    iconName: 'matic_circle_color',
  },
  {
    symbol: 'UNIV2DAIETH',
    name: 'UNIV2DAIETH',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'WSTETH',
    name: 'Wrapped Staked ETH',
    iconName: 'wsteth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'CBETH',
    name: 'Coinbase Wrapped Staked ETH',
    iconName: 'cbeth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'CBBTC',
    name: 'Coinbase Wrapped BTC',
    iconName: 'cbbtc_circle_color',
    rootToken: 'BTC',
  },
  {
    symbol: 'BAT',
    name: 'Basic Attention Token',
    iconName: 'bat_circle_color',
  },
  {
    symbol: 'RENBTC',
    name: 'renBTC',
    iconName: 'renbtc_circle_color',
    rootToken: 'BTC',
  },
  {
    symbol: 'TUSD',
    name: 'Trust token',
    iconName: 'tusd_circle_color',
  },
  {
    symbol: 'KNC',
    name: 'Kyber Network',
    iconName: 'kyber_circle_color',
  },
  {
    symbol: 'PAXUSD',
    name: 'Paxos Standard',
    iconName: 'pax_circle_color',
  },
  {
    symbol: 'USDT',
    name: 'Tether',
    iconName: 'usdt_circle_color',
  },
  {
    symbol: 'USD₮0',
    name: 'USD₮0',
    iconName: 'usd₮0_circle_color',
  },
  {
    symbol: 'COMP',
    name: 'Compound',
    iconName: 'compound_circle_color',
  },
  {
    symbol: 'LRC',
    name: 'Loopring',
    iconName: 'lrc_circle_color',
  },
  {
    symbol: 'ZRX',
    name: '0x',
    iconName: 'zerox_circle_color',
  },
  {
    symbol: 'USDA',
    name: 'Angle USD',
    iconName: 'usda',
  },
  {
    symbol: 'USDC',
    name: 'USD Coin',
    iconName: 'usdc_circle_color',
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    iconName: 'uni_circle_color',
  },
  {
    symbol: 'AAVE',
    name: 'Aave',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'UNIV2USDCETH',
    name: 'UNIV2USDCETH',
    iconName: 'univ2_usdc_eth_circles_color',
  },
  {
    symbol: 'UNIV2DAIUSDC',
    name: 'UNIV2DAIUSDC',
    iconName: 'univ2_dai_usdc_circles_color',
  },
  {
    symbol: 'UNIV2ETHUSDT',
    name: 'UNIV2ETHUSDT',
    iconName: 'univ2_eth_usdt_circles_color',
  },
  {
    symbol: 'UNIV2DAIUSDT',
    name: 'UNIV2DAIUSDT',
    iconName: 'univ2_dai_usdt_circles_color',
  },
  {
    symbol: 'GUNIV3DAIUSDC1',
    name: 'GUNIV3 DAI / USDC 0.05%',
    iconName: 'guniv3_dai_usdc1_circles_color',
  },
  {
    symbol: 'GUNIV3DAIUSDC2',
    name: 'GUNIV3 DAI / USDC 0.01%',
    iconName: 'guniv3_dai_usdc1_circles_color',
  },
  {
    symbol: 'DAI',
    name: 'Dai',
    iconName: 'dai_circle_color',
  },
  {
    symbol: 'RETH',
    name: 'Rocket Pool ETH',
    iconName: 'reth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'GNO',
    name: 'Gnosis',
    iconName: 'gno_circle_color',
  },
  {
    symbol: 'GHO',
    name: 'GHO',
    iconName: 'gho_circle_color',
  },
  {
    symbol: 'SAFE',
    name: 'SAFE',
    iconName: 'safe',
  },
  {
    symbol: 'SDAI',
    name: 'Savings Dai',
    iconName: 'sdai_circle_color',
    rootToken: 'DAI',
  },
  {
    symbol: 'TBTC',
    name: 'Threshold Bitcoin',
    iconName: 'tbtc_circle_color',
    rootToken: 'BTC',
  },
  {
    symbol: 'WLD',
    name: 'Worldcoin',
    iconName: 'wld_circle_color',
  },
  {
    symbol: 'YIELDETH',
    name: 'Real Yield ETH',
    iconName: 'yieldeth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'YIELDBTC',
    name: 'Real Yield BTC',
    iconName: 'yieldbtc_circle_color',
    rootToken: 'BTC',
  },
  {
    symbol: 'LUSD',
    name: 'Liquitity USD',
    iconName: 'lusd_circle_color',
  },
  {
    symbol: 'FRAX',
    name: 'Liquitity USD',
    iconName: 'frax_circle_color',
  },
  {
    symbol: 'SPARK',
    name: 'Spark',
    iconName: 'spark_circle_color',
  },
  {
    symbol: 'USDBC',
    name: 'USD Base Coin',
    iconName: 'usdc_circle_color',
  },
  {
    symbol: 'USDC.E',
    name: 'Bridged USD Coin',
    iconName: 'usdc_circle_color',
  },
  {
    symbol: 'RPL',
    name: 'Rocket Pool',
    iconName: 'rpl_circle',
  },
  {
    symbol: 'CRV',
    name: 'Curve',
    iconName: 'crv_circle',
  },
  {
    symbol: 'BAL',
    name: 'Balancer',
    iconName: 'bal_circle',
  },
  {
    symbol: 'BSDETH',
    name: 'Based ETH',
    iconName: 'bsdeth_circle_color',
  },
  {
    symbol: 'LDO',
    name: 'Lido DAO',
    iconName: 'ldo_circle',
  },
  {
    symbol: 'SUSD',
    name: 'Synth sUSD',
    iconName: 'susd_circle',
  },
  {
    symbol: 'OP',
    name: 'Optimism',
    iconName: 'op_circle',
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    iconName: 'arb_circle',
  },
  {
    symbol: 'STYETH',
    name: 'Staked Yearn Ether',
    iconName: 'styeth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'AJNA',
    name: 'AjnaToken',
    iconName: 'ajna_circle_color',
    rootToken: 'AJNA',
  },
  {
    symbol: 'MORPHO',
    name: 'Morpho Blue',
    iconName: 'morpho_circle_color',
  },
  {
    symbol: 'RBN',
    name: 'Ribbon',
    iconName: 'rbn_circle_color',
    rootToken: 'RBN',
  },
  {
    symbol: 'OSETH',
    name: 'Staked ETH',
    iconName: 'oseth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'WEETH',
    name: 'Wrapped eETH',
    iconName: 'weeth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'APXETH',
    name: 'Autocompounding Pirex Ether',
    iconName: 'apxeth_circle_color',
    rootToken: 'ETH',
  },
  {
    symbol: 'SUSDE',
    name: 'Ethena Staked USDe',
    iconName: 'susde',
  },
  {
    symbol: 'CSETH',
    name: 'ClayStack Staked ETH',
    iconName: 'cseth',
    rootToken: 'ETH',
  },
  {
    symbol: 'DETH',
    name: 'Stakehouse dETH',
    iconName: 'deth',
    rootToken: 'ETH',
  },
  {
    symbol: 'EZETH',
    name: 'Renzo Restaked ETH',
    iconName: 'ezeth',
    rootToken: 'ETH',
  },
  {
    symbol: 'MPETH',
    name: 'MetaPoolETH',
    iconName: 'mpeth',
    rootToken: 'ETH',
  },
  {
    symbol: 'UNIETH',
    name: 'Universal ETH',
    iconName: 'unieth',
    rootToken: 'ETH',
  },
  {
    symbol: 'MEVETH',
    name: 'Mev Liquid Staking',
    iconName: 'meveth',
    rootToken: 'ETH',
  },
  {
    symbol: 'XETH',
    name: 'f(x) Protocol Leveraged ETH',
    iconName: 'xeth',
    rootToken: 'ETH',
  },
  {
    symbol: 'USDE',
    name: 'USDe',
    iconName: 'usde',
    rootToken: 'USD',
  },
  {
    symbol: 'PTWEETH',
    name: 'Pendle PT-weETH',
    iconName: 'question',
    iconUnavailable: true,
  },
  {
    symbol: 'PYUSD',
    name: 'PayPal USD',
    iconName: 'pyusd',
  },
  {
    symbol: 'CRVUSD',
    name: 'Curve.Fi USD Stablecoin',
    iconName: 'crv_circle',
  },
  {
    symbol: 'AETHSDAI',
    name: 'Aave Ethereum sDAI',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHUSDC',
    name: 'Aave Ethereum USDC',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHUSDT',
    name: 'Aave Ethereum USDT',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHDAI',
    name: 'Aave Ethereum DAI',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHPYUSD',
    name: 'Aave Ethereum PYUSD',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHLUSD',
    name: 'Aave Ethereum LUSD',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AUSDC',
    name: 'Aave interest bearing USDC',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'ADAI',
    name: 'Aave interest bearing DAI',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AUSDT',
    name: 'Aave interest bearing USDT',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'CUSDCV3',
    name: 'Compound v3 USDC',
    iconName: 'compound',
  },
  {
    symbol: 'CDAI',
    name: 'Compound Dai',
    iconName: 'compound',
  },
  {
    symbol: 'CUSDC',
    name: 'Compound USDC',
    iconName: 'compound',
  },
  {
    symbol: 'AETHWSTETH',
    name: 'Aave Ethereum Wrapped Staked Ether',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHWETH',
    name: 'Aave Ethereum Wrapped Ether',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHRETH',
    name: 'Aave Ethereum Rocket Pool Ether',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AETHCBETH',
    name: 'Aave Ethereum Coinbase Wrapped Staked Ether',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AWETH',
    name: 'Aave interest bearing Wrapped Ether',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'CETH',
    name: 'Compound Ether',
    iconName: 'compound',
  },
  {
    symbol: 'CWETHV3',
    name: 'Compound v3 Wrapped Ether',
    iconName: 'compound',
  },
  {
    symbol: 'AETHWBTC',
    name: 'Aave Ethereum Wrapped Bitcoin',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'AWBTC',
    name: 'Aave interest bearing Wrapped Bitcoin',
    iconName: 'aave_circle_color',
  },
  {
    symbol: 'DEGEN',
    name: 'Degen',
    iconName: 'degen',
  },
  {
    symbol: 'ENA',
    name: 'Ethena',
    iconName: 'ena',
  },
  {
    symbol: 'SNX',
    name: 'Synthetix Network',
    iconName: 'snx',
  },
  {
    symbol: 'AERO',
    name: 'Aerodrome',
    iconName: 'aero',
  },
  {
    symbol: 'PRIME',
    name: 'Prime',
    iconName: 'prime',
  },
  {
    symbol: 'UNIV2',
    name: 'Uniswap V2',
    iconName: 'uni_circle_color',
  },
  {
    symbol: 'USDS',
    name: 'USDS Stablecoin',
    iconName: 'usds',
  },
  {
    symbol: 'SUSDS',
    name: 'Savings USDS',
    iconName: 'susds',
  },
  {
    symbol: 'SKY',
    name: 'SKY Governance Token',
    iconName: 'sky',
  },
  {
    symbol: 'RSWETH',
    name: 'rswETH',
    iconName: 'rsweth',
  },
  {
    symbol: 'RSETH',
    name: 'rsETH',
    iconName: 'rseth',
  },
  {
    symbol: 'LBTC',
    name: 'Lombard Staked Bitcoin',
    iconName: 'lbtc',
  },
  {
    symbol: 'SWBTC',
    name: 'swBTC',
    iconName: 'swbtc',
  },
  {
    symbol: 'SYRUPUSDC',
    name: 'Syrup USDC',
    iconName: 'syrupusdc',
  },
  {
    symbol: 'WOETH',
    name: 'Wrapped OETH',
    iconName: 'woeth',
  },
  {
    symbol: 'EURC',
    name: 'EURC',
    iconName: 'eurc',
  },
  {
    symbol: 'WUSDL',
    name: 'WUSDL',
    iconName: 'wusdl',
  },
  {
    symbol: 'SUMR',
    name: 'SUMR',
    iconName: 'sumr',
  },
  {
    symbol: 'MBASIS',
    name: 'Midas Basis Trading Token',
    iconName: 'mbasis',
  },
  // NOT SUPPORTED ICONS
  {
    symbol: 'UNIV2WBTCETH',
    name: 'UNIV2WBTCETH',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'UNIV2LINKETH',
    name: 'UNIV2LINKETH',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'UNIV2UNIETH',
    name: 'UNIV2UNIETH',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'UNIV2WBTCDAI',
    name: 'UNIV2WBTCDAI',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'UNIV2AAVEETH',
    name: 'UNIV2AAVEETH',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'CRVV1ETHSTETH',
    name: 'CRVV1ETHSTETH',
    iconName: 'not_supported_icon',
  },
  {
    symbol: 'S',
    name: 'Sonic',
    iconName: 'sonic_circle_color',
  },
]
