export enum GraphRoleName {
  CURATOR_ROLE = 'CURATOR_ROLE',
  KEEPER_ROLE = 'KEEPER_ROLE',
  COMMANDER_ROLE = 'COMMANDER_ROLE',
  WHITELIST_ROLE = 'WHITELIST_ROLE',
  GOVERNOR_ROLE = 'GOVERNOR_ROLE',
  SUPER_KEEPER_ROLE = 'SUPER_KEEPER_ROLE',
  ADMIRALS_QUARTERS_ROLE = 'ADMIRALS_QUARTERS_ROLE',
  DECAY_CONTROLLER_ROLE = 'DECAY_CONTROLLER_ROLE',
}
