/** Global (protocol-wide) access-control roles for institutional deployments. */
export enum InstiGlobalRoles {
  GOVERNOR_ROLE = 'GOVERNOR_ROLE',
  KEEPER_ROLE = 'KEEPER_ROLE',
  SUPER_KEEPER_ROLE = 'SUPER_KEEPER_ROLE',
  CURATOR_ROLE = 'CURATOR_ROLE',
  GUARDIAN_ROLE = 'GUARDIAN_ROLE',
  COMMANDER_ROLE = 'COMMANDER_ROLE',
  ADMIRALS_QUARTERS_ROLE = 'ADMIRALS_QUARTERS_ROLE',
  DECAY_CONTROLLER_ROLE = 'DECAY_CONTROLLER_ROLE',
  WHITELIST_ROLE = 'WHITELIST_ROLE',
  FOUNDATION_ROLE = 'FOUNDATION_ROLE',
}
