/// <reference types="vite-plugin-svgr/client" />
/* eslint-disable @typescript-eslint/consistent-type-imports */
/* eslint-disable camelcase */

import { lazy } from 'react'

const customLazy = (importFn: () => Promise<typeof import('*.svg?react')>) =>
  lazy(async () => ({ default: (await importFn()).default }))

export const icons = {
  aave_cbETH_usdc: customLazy(() => import('./icons/aave_cbETH_usdc.svg?react')),
  aave_circle_color: customLazy(() => import('./icons/aave_circle_color.svg?react')),
  aave_eth_usdc: customLazy(() => import('./icons/aave_eth_usdc.svg?react')),
  aave_steth_eth: customLazy(() => import('./icons/aave_steth_eth.svg?react')),
  aave_steth_usdc: customLazy(() => import('./icons/aave_steth_usdc.svg?react')),
  aave_wbtc_usdc: customLazy(() => import('./icons/aave_wbtc_usdc.svg?react')),
  aero: customLazy(() => import('./icons/aero.svg?react')),
  ajna_circle_color: customLazy(() => import('./icons/ajna_circle_color.svg?react')),
  apxeth_circle_color: customLazy(() => import('./icons/apxeth_circle_color.svg?react')),
  arb: customLazy(() => import('./icons/arb.svg?react')),
  arb_circle: customLazy(() => import('./icons/arb_circle.svg?react')),
  augur: customLazy(() => import('./icons/augur.svg?react')),
  augur_circle_color: customLazy(() => import('./icons/augur_circle_color.svg?react')),
  augur_color: customLazy(() => import('./icons/augur_color.svg?react')),
  bal: customLazy(() => import('./icons/bal.svg?react')),
  bal_circle: customLazy(() => import('./icons/bal_circle.svg?react')),
  bal_circle_color: customLazy(() => import('./icons/bal_circle_color.svg?react')),
  bat: customLazy(() => import('./icons/bat.svg?react')),
  bat_circle_color: customLazy(() => import('./icons/bat_circle_color.svg?react')),
  bat_color: customLazy(() => import('./icons/bat_color.svg?react')),
  bridge: customLazy(() => import('./icons/bridge.svg?react')),
  btc_circle_color: customLazy(() => import('./icons/btc_circle_color.svg?react')),
  btc_circle_mono: customLazy(() => import('./icons/btc_circle_mono.svg?react')),
  cbeth_circle_color: customLazy(() => import('./icons/cbeth_circle_color.svg?react')),
  cbeth_eth: customLazy(() => import('./icons/cbeth_eth.svg?react')),
  cbeth_usdc: customLazy(() => import('./icons/cbeth_usdc.svg?react')),
  chai: customLazy(() => import('./icons/chai.svg?react')),
  chai_circle_color: customLazy(() => import('./icons/chai_circle_color.svg?react')),
  chai_color: customLazy(() => import('./icons/chai_color.svg?react')),
  chainlink: customLazy(() => import('./icons/chainlink.svg?react')),
  chainlink_circle_color: customLazy(() => import('./icons/chainlink_circle_color.svg?react')),
  chainlink_color: customLazy(() => import('./icons/chainlink_color.svg?react')),
  compound: customLazy(() => import('./icons/compound.svg?react')),
  compound_circle_color: customLazy(() => import('./icons/compound_circle_color.svg?react')),
  compound_color: customLazy(() => import('./icons/compound_color.svg?react')),
  crv: customLazy(() => import('./icons/crv.svg?react')),
  crv_circle: customLazy(() => import('./icons/crv_circle.svg?react')),
  cseth: customLazy(() => import('./icons/cseth.svg?react')),
  dai: customLazy(() => import('./icons/dai.svg?react')),
  dai_circle_color: customLazy(() => import('./icons/dai_circle_color.svg?react')),
  dai_color: customLazy(() => import('./icons/dai_color.svg?react')),
  degen: customLazy(() => import('./icons/degen.svg?react')),
  not_supported_icon: customLazy(() => import('./icons/not_supported_icon.svg?react')),
  deth: customLazy(() => import('./icons/deth.svg?react')),
  digix_circle_color: customLazy(() => import('./icons/digix_circle_color.svg?react')),
  ena: customLazy(() => import('./icons/ena.svg?react')),
  eth_circle_color: customLazy(() => import('./icons/eth_circle_color.svg?react')),
  eth_circle_mono: customLazy(() => import('./icons/eth_circle_mono.svg?react')),
  eth_usdc: customLazy(() => import('./icons/eth_usdc.svg?react')),
  ether: customLazy(() => import('./icons/ether.svg?react')),
  ether_circle_color: customLazy(() => import('./icons/ether_circle_color.svg?react')),
  ether_color: customLazy(() => import('./icons/ether_color.svg?react')),
  euro_circle_color: customLazy(() => import('./icons/euro_circle_color.svg?react')),
  exchange: customLazy(() => import('./icons/exchange.svg?react')),
  ezeth: customLazy(() => import('./icons/ezeth.svg?react')),
  frax_circle_color: customLazy(() => import('./icons/frax_circle_color.svg?react')),
  gemini: customLazy(() => import('./icons/gemini.svg?react')),
  gemini_circle_color: customLazy(() => import('./icons/gemini_circle_color.svg?react')),
  gemini_color: customLazy(() => import('./icons/gemini_color.svg?react')),
  gno_circle_color: customLazy(() => import('./icons/gno_circle_color.svg?react')),
  gho_circle_color: customLazy(() => import('./icons/gho_circle_color.svg?react')),
  golem_circle_color: customLazy(() => import('./icons/golem_circle_color.svg?react')),
  guniv3_dai_usdc1_circles_color: customLazy(
    () => import('./icons/guniv3_dai_usdc1_circles_color.svg?react'),
  ),
  gusd_circle_color: customLazy(() => import('./icons/gusd_circle_color.svg?react')),
  gusd_circle_mono: customLazy(() => import('./icons/gusd_circle_mono.svg?react')),
  knc_circle_color: customLazy(() => import('./icons/knc_circle_color.svg?react')),
  kyber: customLazy(() => import('./icons/kyber.svg?react')),
  kyber_circle_color: customLazy(() => import('./icons/kyber_circle_color.svg?react')),
  kyber_color: customLazy(() => import('./icons/kyber_color.svg?react')),
  latamex: customLazy(() => import('./icons/latamex.svg?react')),
  ldo: customLazy(() => import('./icons/ldo.svg?react')),
  ldo_circle: customLazy(() => import('./icons/ldo_circle.svg?react')),
  link: customLazy(() => import('./icons/link.svg?react')),
  link_circle_color: customLazy(() => import('./icons/link_circle_color.svg?react')),
  link_circle_mono: customLazy(() => import('./icons/link_circle_mono.svg?react')),
  lrc: customLazy(() => import('./icons/lrc.svg?react')),
  lrc_circle_color: customLazy(() => import('./icons/lrc_circle_color.svg?react')),
  lrc_color: customLazy(() => import('./icons/lrc_color.svg?react')),
  lusd_circle_color: customLazy(() => import('./icons/lusd_circle_color.svg?react')),
  maker: customLazy(() => import('./icons/maker.svg?react')),
  maker_circle_color: customLazy(() => import('./icons/maker_circle_color.svg?react')),
  maker_color: customLazy(() => import('./icons/maker_color.svg?react')),
  mana: customLazy(() => import('./icons/mana.svg?react')),
  mana_circle_color: customLazy(() => import('./icons/mana_circle_color.svg?react')),
  mana_circle_mono: customLazy(() => import('./icons/mana_circle_mono.svg?react')),
  mana_color: customLazy(() => import('./icons/mana_color.svg?react')),
  matic_circle_color: customLazy(() => import('./icons/matic_circle_color.svg?react')),
  matic_circle_mono: customLazy(() => import('./icons/matic_circle_mono.svg?react')),
  menu: customLazy(() => import('./icons/menu.svg?react')),
  meveth: customLazy(() => import('./icons/meveth.svg?react')),
  mkr_circle_color: customLazy(() => import('./icons/mkr_circle_color.svg?react')),
  moonpay: customLazy(() => import('./icons/moonpay.svg?react')),
  morpho_circle_color: customLazy(() => import('./icons/morpho_circle_color.svg?react')),
  mpeth: customLazy(() => import('./icons/mpeth.svg?react')),
  omisego: customLazy(() => import('./icons/omisego.svg?react')),
  omisego_circle_color: customLazy(() => import('./icons/omisego_circle_color.svg?react')),
  omisego_color: customLazy(() => import('./icons/omisego_color.svg?react')),
  op: customLazy(() => import('./icons/op.svg?react')),
  op_circle: customLazy(() => import('./icons/op_circle.svg?react')),
  open_in_new_tab: customLazy(() => import('./icons/open_in_new_tab.svg?react')),
  oseth_circle_color: customLazy(() => import('./icons/oseth_circle_color.svg?react')),
  pax: customLazy(() => import('./icons/pax.svg?react')),
  pax_circle_color: customLazy(() => import('./icons/pax_circle_color.svg?react')),
  pax_color: customLazy(() => import('./icons/pax_color.svg?react')),
  prime: customLazy(() => import('./icons/prime.svg?react')),
  pyusd: customLazy(() => import('./icons/pyusd.svg?react')),
  question: customLazy(() => import('./icons/question.svg?react')),
  question_mark: customLazy(() => import('./icons/question_mark.svg?react')),
  question_o: customLazy(() => import('./icons/question_o.svg?react')),
  rbn_circle_color: customLazy(() => import('./icons/rbn_circle_color.svg?react')),
  renbtc_circle_color: customLazy(() => import('./icons/renbtc_circle_color.svg?react')),
  reth_circle_color: customLazy(() => import('./icons/reth_circle_color.svg?react')),
  reth_eth: customLazy(() => import('./icons/reth_eth.svg?react')),
  reth_usdc: customLazy(() => import('./icons/reth_usdc.svg?react')),
  rpl: customLazy(() => import('./icons/rpl.svg?react')),
  rpl_circle: customLazy(() => import('./icons/rpl_circle.svg?react')),
  safe: customLazy(() => import('./icons/safe.svg?react')),
  sai: customLazy(() => import('./icons/sai.svg?react')),
  sai_circle_color: customLazy(() => import('./icons/sai_circle_color.svg?react')),
  sai_color: customLazy(() => import('./icons/sai_color.svg?react')),
  sdai_circle_color: customLazy(() => import('./icons/sdai_circle_color.svg?react')),
  snx: customLazy(() => import('./icons/snx.svg?react')),
  spark_circle_color: customLazy(() => import('./icons/spark_circle_color.svg?react')),
  steth_circle_color: customLazy(() => import('./icons/steth_circle_color.svg?react')),
  steth_eth: customLazy(() => import('./icons/steth_eth.svg?react')),
  steth_usdc: customLazy(() => import('./icons/steth_usdc.svg?react')),
  styeth_circle_color: customLazy(() => import('./icons/styeth_circle_color.svg?react')),
  susd: customLazy(() => import('./icons/susd.svg?react')),
  susd_circle: customLazy(() => import('./icons/susd_circle.svg?react')),
  susde: customLazy(() => import('./icons/susde.svg?react')),
  tbtc_circle_color: customLazy(() => import('./icons/tbtc_circle_color.svg?react')),
  tusd: customLazy(() => import('./icons/tusd.svg?react')),
  tusd_circle_color: customLazy(() => import('./icons/tusd_circle_color.svg?react')),
  tusd_color: customLazy(() => import('./icons/tusd_color.svg?react')),
  uni_circle_color: customLazy(() => import('./icons/uni_circle_color.svg?react')),
  uni_circle_mono: customLazy(() => import('./icons/uni_circle_mono.svg?react')),
  uni_lp_circle_color: customLazy(() => import('./icons/uni_lp_circle_color.svg?react')),
  uni_lp_circle_mono: customLazy(() => import('./icons/uni_lp_circle_mono.svg?react')),
  unieth: customLazy(() => import('./icons/unieth.svg?react')),
  univ2_dai_usdc_circles_color: customLazy(
    () => import('./icons/univ2_dai_usdc_circles_color.svg?react'),
  ),
  univ2_dai_usdt_circles_color: customLazy(
    () => import('./icons/univ2_dai_usdt_circles_color.svg?react'),
  ),
  univ2_eth_usdt_circles_color: customLazy(
    () => import('./icons/univ2_eth_usdt_circles_color.svg?react'),
  ),
  univ2_usdc_eth_circles_color: customLazy(
    () => import('./icons/univ2_usdc_eth_circles_color.svg?react'),
  ),
  usd_circle_color: customLazy(() => import('./icons/usd_circle_color.svg?react')),
  usda: customLazy(() => import('./icons/usda.svg?react')),
  usdc: customLazy(() => import('./icons/usdc.svg?react')),
  usdc_circle_color: customLazy(() => import('./icons/usdc_circle_color.svg?react')),
  usde: customLazy(() => import('./icons/usde.svg?react')),
  usdp_circle_color: customLazy(() => import('./icons/usdp_circle_color.svg?react')),
  usdt: customLazy(() => import('./icons/usdt.svg?react')),
  usdt_circle_color: customLazy(() => import('./icons/usdt_circle_color.svg?react')),
  usdt_color: customLazy(() => import('./icons/usdt_color.svg?react')),
  wbtc: customLazy(() => import('./icons/wbtc.svg?react')),
  wbtc_circle_color: customLazy(() => import('./icons/wbtc_circle_color.svg?react')),
  wbtc_color: customLazy(() => import('./icons/wbtc_color.svg?react')),
  wbtc_usdc: customLazy(() => import('./icons/wbtc_usdc.svg?react')),
  weeth_circle_color: customLazy(() => import('./icons/weeth_circle_color.svg?react')),
  weth_circle_color: customLazy(() => import('./icons/weth_circle_color.svg?react')),
  wld_circle_color: customLazy(() => import('./icons/wld_circle_color.svg?react')),
  wsteth_circle_color: customLazy(() => import('./icons/wsteth_circle_color.svg?react')),
  wyre: customLazy(() => import('./icons/wyre.svg?react')),
  xeth: customLazy(() => import('./icons/xeth.svg?react')),
  yen_circle_color: customLazy(() => import('./icons/yen_circle_color.svg?react')),
  yfi_circle_color: customLazy(() => import('./icons/yfi_circle_color.svg?react')),
  yfi_circle_mono: customLazy(() => import('./icons/yfi_circle_mono.svg?react')),
  yieldbtc_circle_color: customLazy(() => import('./icons/yieldbtc_circle_color.svg?react')),
  yieldeth_circle_color: customLazy(() => import('./icons/yieldeth_circle_color.svg?react')),
  zerox: customLazy(() => import('./icons/zerox.svg?react')),
  zerox_circle_color: customLazy(() => import('./icons/zerox_circle_color.svg?react')),
  zerox_color: customLazy(() => import('./icons/zerox_color.svg?react')),
  bsdeth_circle_color: customLazy(() => import('./icons/bsdeth_circle_color.svg?react')),
  autoBuy: customLazy(() => import('./icons/autoBuy.svg?react')),
  autoSell: customLazy(() => import('./icons/autoSell.svg?react')),
  stopLoss: customLazy(() => import('./icons/stopLoss.svg?react')),
  trailingStopLoss: customLazy(() => import('./icons/stopLoss.svg?react')),
  takeProfit: customLazy(() => import('./icons/takeProfit.svg?react')),
  partialTakeProfit: customLazy(() => import('./icons/takeProfit.svg?react')),
  autoTakeProfit: customLazy(() => import('./icons/takeProfit.svg?react')),
  constantMultiple: customLazy(() => import('./icons/takeProfit.svg?react')),
  rays: customLazy(() => import('./icons/rays.svg?react')),
  chevron_down: customLazy(() => import('./icons/chevron_down.svg?react')),
  chevron_up: customLazy(() => import('./icons/chevron_up.svg?react')),
  chevron_left: customLazy(() => import('./icons/chevron_left.svg?react')),
  chevron_right: customLazy(() => import('./icons/chevron_right.svg?react')),
  search_icon: customLazy(() => import('./icons/search_icon.svg?react')),
  tooltip: customLazy(() => import('./icons/tooltip.svg?react')),
  checkmark_colorful: customLazy(() => import('./icons/checkmark_colorful.svg?react')),
  checkmark: customLazy(() => import('./icons/checkmark.svg?react')),
  close: customLazy(() => import('./icons/close.svg?react')),
  close_colorful: customLazy(() => import('./icons/close_colorful.svg?react')),
  close_squared: customLazy(() => import('./icons/close_squared.svg?react')),
  radio_button: customLazy(() => import('./icons/radio_button.svg?react')),
  radio_button_checked: customLazy(() => import('./icons/radio_button_checked.svg?react')),
  rseth: customLazy(() => import('./icons/rseth.svg?react')),
  rsweth: customLazy(() => import('./icons/rsweth.svg?react')),
  swbtc: customLazy(() => import('./icons/swbtc.svg?react')),
  lbtc: customLazy(() => import('./icons/lbtc.svg?react')),
  syrupusdc: customLazy(() => import('./icons/syrupusdc.svg?react')),
  woeth: customLazy(() => import('./icons/woeth.svg?react')),
  sky: customLazy(() => import('./icons/sky.svg?react')),
  usds: customLazy(() => import('./icons/usds.svg?react')),
  susds: customLazy(() => import('./icons/susds.svg?react')),
  cog: customLazy(() => import('./icons/cog.svg?react')),
  user: customLazy(() => import('./icons/user.svg?react')),
  rebalancing: customLazy(() => import('./icons/rebalancing.svg?react')),
  wsuperoethb: customLazy(() => import('./icons/wsuperoethb.svg?react')),
  arrow_decrease: customLazy(() => import('./icons/arrow_decrease.svg?react')),
  arrow_increase: customLazy(() => import('./icons/arrow_increase.svg?react')),
  stars: customLazy(() => import('./icons/stars.svg?react')),
  chain_security: customLazy(() => import('./icons/chain_security.svg?react')),
  bug: customLazy(() => import('./icons/bug.svg?react')),
  quant_stamp: customLazy(() => import('./icons/quant_stamp.svg?react')),
  trail_of_bits: customLazy(() => import('./icons/trail_of_bits.svg?react')),
  person: customLazy(() => import('./icons/person.svg?react')),
  discord: customLazy(() => import('./icons/discord.svg?react')),
  edit: customLazy(() => import('./icons/edit.svg?react')),
  send: customLazy(() => import('./icons/send.svg?react')),
  arrow_forward: customLazy(() => import('./icons/arrow_forward.svg?react')),
  base: customLazy(() => import('./icons/base.svg?react')),
  network_ethereum: customLazy(() => import('./icons/network_ethereum.svg?react')),
  network_arbitrum: customLazy(() => import('./icons/network_arbitrum.svg?react')),
  network_optimism: customLazy(() => import('./icons/network_optimism.svg?react')),
  network_base: customLazy(() => import('./icons/network_base.svg?react')),
  withdraw: customLazy(() => import('./icons/withdraw.svg?react')),
  summer_illustration_check: customLazy(
    () => import('./icons/summer_illustration_check.svg?react'),
  ),
  summer_illustration_email: customLazy(
    () => import('./icons/summer_illustration_email.svg?react'),
  ),
  summer_illustration_failed: customLazy(
    () => import('./icons/summer_illustration_failed.svg?react'),
  ),
  summer_illustration_gas_fee: customLazy(
    () => import('./icons/summer_illustration_gas_fee.svg?react'),
  ),
  summer_illustration_identity: customLazy(
    () => import('./icons/summer_illustration_identity.svg?react'),
  ),
  summer_illustration_logo: customLazy(() => import('./icons/summer_illustration_logo.svg?react')),
  summer_illustration_passkey: customLazy(
    () => import('./icons/summer_illustration_passkey.svg?react'),
  ),
  summer_illustration_shield: customLazy(
    () => import('./icons/summer_illustration_shield.svg?react'),
  ),
  summer_illustration_switch: customLazy(
    () => import('./icons/summer_illustration_switch.svg?react'),
  ),
  summer_illustration_transak_logo: customLazy(
    () => import('./icons/summer_illustration_transak_logo.svg?react'),
  ),
  summer_illustration_verification: customLazy(
    () => import('./icons/summer_illustration_verification.svg?react'),
  ),
}
