/**
 * List of countries supported by Transak with their respective alpha-2, alpha-3 codes, currency codes, and names.
 */
const transakCountries = [
  {
    alpha2: 'AS',
    alpha3: 'ASM',
    currencyCode: 'EUR',
    name: 'American Samoa',
  },
  {
    alpha2: 'AD',
    alpha3: 'AND',
    currencyCode: 'EUR',
    name: 'Andorra',
  },
  {
    alpha2: 'AO',
    alpha3: 'AGO',
    currencyCode: 'AOA',
    name: 'Angola',
  },
  {
    alpha2: 'AI',
    alpha3: 'AIA',
    currencyCode: 'XCD',
    name: 'Anguilla',
  },
  {
    alpha2: 'AG',
    alpha3: 'ATG',
    currencyCode: 'XCD',
    name: 'Antigua and Barbuda',
  },
  {
    alpha2: 'AR',
    alpha3: 'ARG',
    currencyCode: 'ARS',
    name: 'Argentina',
  },
  {
    alpha2: 'AW',
    alpha3: 'ABW',
    currencyCode: 'ANG',
    name: 'Aruba',
  },
  {
    alpha2: 'AU',
    alpha3: 'AUS',
    currencyCode: 'AUD',
    name: 'Australia',
  },
  {
    alpha2: 'AT',
    alpha3: 'AUT',
    currencyCode: 'EUR',
    name: 'Austria',
  },
  {
    alpha2: 'BS',
    alpha3: 'BHS',
    currencyCode: 'BSD',
    name: 'Bahamas',
  },
  {
    alpha2: 'BH',
    alpha3: 'BHR',
    currencyCode: 'BHD',
    name: 'Bahrain',
  },
  {
    alpha2: 'BE',
    alpha3: 'BEL',
    currencyCode: 'EUR',
    name: 'Belgium',
  },
  {
    alpha2: 'BZ',
    alpha3: 'BLZ',
    currencyCode: 'BZD',
    name: 'Belize',
  },
  {
    alpha2: 'BJ',
    alpha3: 'BEN',
    currencyCode: 'XOF',
    name: 'Benin',
  },
  {
    alpha2: 'BM',
    alpha3: 'BMU',
    currencyCode: 'BMD',
    name: 'Bermuda',
  },
  {
    alpha2: 'BT',
    alpha3: 'BTN',
    currencyCode: 'INR',
    name: 'Bhutan',
  },
  {
    alpha2: 'BQ',
    alpha3: 'BES',
    currencyCode: 'USD',
    name: 'Bonaire, Sint Eustatius And Saba',
  },
  {
    alpha2: 'BR',
    alpha3: 'BRA',
    currencyCode: 'BRL',
    name: 'Brazil',
  },
  {
    alpha2: 'BN',
    alpha3: 'BRN',
    currencyCode: 'BND',
    name: 'Brunei Darussalam',
  },
  {
    alpha2: 'CV',
    alpha3: 'CPV',
    currencyCode: 'CVE',
    name: 'Cabo Verde',
  },
  {
    alpha2: 'KH',
    alpha3: 'KHM',
    currencyCode: 'KHR',
    name: 'Cambodia',
  },
  {
    alpha2: 'CA',
    alpha3: 'CAN',
    currencyCode: 'CAD',
    name: 'Canada',
  },
  {
    alpha2: 'KY',
    alpha3: 'CYM',
    currencyCode: 'KYD',
    name: 'Cayman Islands',
  },
  {
    alpha2: 'TD',
    alpha3: 'TCD',
    currencyCode: 'XAF',
    name: 'Chad',
  },
  {
    alpha2: 'CL',
    alpha3: 'CHL',
    currencyCode: 'CLP',
    name: 'Chile',
  },
  {
    alpha2: 'CX',
    alpha3: 'CXR',
    currencyCode: 'AUD',
    name: 'Christmas Island',
  },
  {
    alpha2: 'CC',
    alpha3: 'CCK',
    currencyCode: 'AUD',
    name: 'Cocos (Keeling) Islands',
  },
  {
    alpha2: 'CO',
    alpha3: 'COL',
    currencyCode: 'COP',
    name: 'Colombia',
  },
  {
    alpha2: 'KM',
    alpha3: 'COM',
    currencyCode: 'KMF',
    name: 'Comoros (the)',
  },
  {
    alpha2: 'CK',
    alpha3: 'COK',
    currencyCode: 'NZD',
    name: 'Cook Islands',
  },
  {
    alpha2: 'CR',
    alpha3: 'CRI',
    currencyCode: 'CRC',
    name: 'Costa Rica',
  },
  {
    alpha2: 'CW',
    alpha3: 'CUW',
    currencyCode: 'ANG',
    name: 'Curacao',
  },
  {
    alpha2: 'CY',
    alpha3: 'CYP',
    currencyCode: 'EUR',
    name: 'Cyprus',
  },
  {
    alpha2: 'CZ',
    alpha3: 'CZE',
    currencyCode: 'CZK',
    name: 'Czech Republic',
  },
  {
    alpha2: 'CI',
    alpha3: 'CIV',
    currencyCode: 'XOF',
    name: "Côte d'Ivoire",
  },
  {
    alpha2: 'DK',
    alpha3: 'DNK',
    currencyCode: 'EUR',
    name: 'Denmark',
  },
  {
    alpha2: 'DJ',
    alpha3: 'DJI',
    currencyCode: 'DJF',
    name: 'Djibouti',
  },
  {
    alpha2: 'DM',
    alpha3: 'DMA',
    currencyCode: 'XCD',
    name: 'Dominica',
  },
  {
    alpha2: 'DO',
    alpha3: 'DOM',
    currencyCode: 'DOP',
    name: 'Dominican Republic',
  },
  {
    alpha2: 'EC',
    alpha3: 'ECU',
    currencyCode: 'ECS',
    name: 'Ecuador',
  },
  {
    alpha2: 'SV',
    alpha3: 'SLV',
    currencyCode: 'SVC',
    name: 'El Salvador',
  },
  {
    alpha2: 'GQ',
    alpha3: 'GNQ',
    currencyCode: 'XAF',
    name: 'Equatorial Guinea',
  },
  {
    alpha2: 'EE',
    alpha3: 'EST',
    currencyCode: 'EUR',
    name: 'Estonia',
  },
  {
    alpha2: 'SZ',
    alpha3: 'SWZ',
    currencyCode: 'SZL',
    name: 'Eswatini',
  },
  {
    alpha2: 'FK',
    alpha3: 'FLK',
    currencyCode: 'FKP',
    name: 'Falkland Islands (the) [Malvinas]',
  },
  {
    alpha2: 'FO',
    alpha3: 'FRO',
    currencyCode: 'DKK',
    name: 'Faroe Islands',
  },
  {
    alpha2: 'FJ',
    alpha3: 'FJI',
    currencyCode: 'FJD',
    name: 'Fiji',
  },
  {
    alpha2: 'FI',
    alpha3: 'FIN',
    currencyCode: 'EUR',
    name: 'Finland',
  },
  {
    alpha2: 'FR',
    alpha3: 'FRA',
    currencyCode: 'EUR',
    name: 'France',
  },
  {
    alpha2: 'GF',
    alpha3: 'GUF',
    currencyCode: 'EUR',
    name: 'French Guiana',
  },
  {
    alpha2: 'PF',
    alpha3: 'PYF',
    currencyCode: 'XPF',
    name: 'French Polynesia',
  },
  {
    alpha2: 'GA',
    alpha3: 'GAB',
    currencyCode: 'XAF',
    name: 'Gabon',
  },
  {
    alpha2: 'GE',
    alpha3: 'GEO',
    currencyCode: 'GEL',
    name: 'Georgia',
  },
  {
    alpha2: 'DE',
    alpha3: 'DEU',
    currencyCode: 'EUR',
    name: 'Germany',
  },
  {
    alpha2: 'GH',
    alpha3: 'GHA',
    currencyCode: 'GHS',
    name: 'Ghana',
  },
  {
    alpha2: 'GR',
    alpha3: 'GRC',
    currencyCode: 'EUR',
    name: 'Greece',
  },
  {
    alpha2: 'GL',
    alpha3: 'GRL',
    currencyCode: 'DKK',
    name: 'Greenland',
  },
  {
    alpha2: 'GD',
    alpha3: 'GRD',
    currencyCode: 'XCD',
    name: 'Grenada',
  },
  {
    alpha2: 'GP',
    alpha3: 'GLP',
    currencyCode: 'EUR',
    name: 'Guadeloupe',
  },
  {
    alpha2: 'GU',
    alpha3: 'GUM',
    currencyCode: 'USD',
    name: 'Guam',
  },
  {
    alpha2: 'GT',
    alpha3: 'GTM',
    currencyCode: 'GTQ',
    name: 'Guatemala',
  },
  {
    alpha2: 'HM',
    alpha3: 'HMD',
    currencyCode: 'AUD',
    name: 'Heard Island And Mcdonald Islands',
  },
  {
    alpha2: 'HN',
    alpha3: 'HND',
    currencyCode: 'HNL',
    name: 'Honduras',
  },
  {
    alpha2: 'HK',
    alpha3: 'HKG',
    currencyCode: 'HKD',
    name: 'Hong Kong',
  },
  {
    alpha2: 'HU',
    alpha3: 'HUN',
    currencyCode: 'HUF',
    name: 'Hungary',
  },
  {
    alpha2: 'IS',
    alpha3: 'ISL',
    currencyCode: 'ISK',
    name: 'Iceland',
  },
  {
    alpha2: 'IN',
    alpha3: 'IND',
    currencyCode: 'INR',
    name: 'India',
  },
  {
    alpha2: 'ID',
    alpha3: 'IDN',
    currencyCode: 'IDR',
    name: 'Indonesia',
  },
  {
    alpha2: 'IE',
    alpha3: 'IRL',
    currencyCode: 'EUR',
    name: 'Ireland',
  },
  {
    alpha2: 'IL',
    alpha3: 'ISR',
    currencyCode: 'ILS',
    name: 'Israel',
  },
  {
    alpha2: 'IT',
    alpha3: 'ITA',
    currencyCode: 'EUR',
    name: 'Italy',
  },
  {
    alpha2: 'JP',
    alpha3: 'JPN',
    currencyCode: 'JPY',
    name: 'Japan',
  },
  {
    alpha2: 'KZ',
    alpha3: 'KAZ',
    currencyCode: 'KZT',
    name: 'Kazakhstan',
  },
  {
    alpha2: 'KI',
    alpha3: 'KIR',
    currencyCode: 'AUD',
    name: 'Kiribati',
  },
  {
    alpha2: 'KW',
    alpha3: 'KWT',
    currencyCode: 'KWD',
    name: 'Kuwait',
  },
  {
    alpha2: 'KG',
    alpha3: 'KGZ',
    currencyCode: 'KGS',
    name: 'Kyrgyzstan',
  },
  {
    alpha2: 'LA',
    alpha3: 'LAO',
    currencyCode: 'LAK',
    name: "Lao People's Democratic Republic",
  },
  {
    alpha2: 'LV',
    alpha3: 'LVA',
    currencyCode: 'EUR',
    name: 'Latvia',
  },
  {
    alpha2: 'LS',
    alpha3: 'LSO',
    currencyCode: 'ZAR',
    name: 'Lesotho',
  },
  {
    alpha2: 'LI',
    alpha3: 'LIE',
    currencyCode: 'CHF',
    name: 'Liechtenstein',
  },
  {
    alpha2: 'LT',
    alpha3: 'LTU',
    currencyCode: 'LTL',
    name: 'Lithuania',
  },
  {
    alpha2: 'LU',
    alpha3: 'LUX',
    currencyCode: 'EUR',
    name: 'Luxembourg',
  },
  {
    alpha2: 'MG',
    alpha3: 'MDG',
    currencyCode: 'MGA',
    name: 'Madagascar',
  },
  {
    alpha2: 'MW',
    alpha3: 'MWI',
    currencyCode: 'MWK',
    name: 'Malawi',
  },
  {
    alpha2: 'MY',
    alpha3: 'MYS',
    currencyCode: 'MYR',
    name: 'Malaysia',
  },
  {
    alpha2: 'MT',
    alpha3: 'MLT',
    currencyCode: 'EUR',
    name: 'Malta',
  },
  {
    alpha2: 'MH',
    alpha3: 'MHL',
    currencyCode: 'USD',
    name: 'Marshall Islands',
  },
  {
    alpha2: 'MQ',
    alpha3: 'MTQ',
    currencyCode: 'EUR',
    name: 'Martinique',
  },
  {
    alpha2: 'MR',
    alpha3: 'MRT',
    currencyCode: 'MRU',
    name: 'Mauritania',
  },
  {
    alpha2: 'MU',
    alpha3: 'MUS',
    currencyCode: 'MUR',
    name: 'Mauritius',
  },
  {
    alpha2: 'YT',
    alpha3: 'MYT',
    currencyCode: 'EUR',
    name: 'Mayotte',
  },
  {
    alpha2: 'MX',
    alpha3: 'MEX',
    currencyCode: 'MXN',
    name: 'Mexico',
  },
  {
    alpha2: 'FM',
    alpha3: 'FSM',
    currencyCode: 'USD',
    name: 'Micronesia (Federated States of)',
  },
  {
    alpha2: 'MD',
    alpha3: 'MDA',
    currencyCode: 'MDL',
    name: 'Moldova, Republic of',
  },
  {
    alpha2: 'MC',
    alpha3: 'MCO',
    currencyCode: 'EUR',
    name: 'Monaco',
  },
  {
    alpha2: 'MN',
    alpha3: 'MNG',
    currencyCode: 'MNT',
    name: 'Mongolia',
  },
  {
    alpha2: 'ME',
    alpha3: 'MNE',
    currencyCode: 'EUR',
    name: 'Montenegro',
  },
  {
    alpha2: 'MS',
    alpha3: 'MSR',
    currencyCode: 'XCD',
    name: 'Montserrat',
  },
  {
    alpha2: 'NR',
    alpha3: 'NRU',
    currencyCode: 'AUD',
    name: 'Nauru',
  },
  {
    alpha2: 'NL',
    alpha3: 'NLD',
    currencyCode: 'EUR',
    name: 'Netherlands',
  },
  {
    alpha2: 'NC',
    alpha3: 'NCL',
    currencyCode: 'XPF',
    name: 'New Caledonia',
  },
  {
    alpha2: 'NZ',
    alpha3: 'NZL',
    currencyCode: 'NZD',
    name: 'New Zealand',
  },
  {
    alpha2: 'NU',
    alpha3: 'NIU',
    currencyCode: 'NZD',
    name: 'Niue',
  },
  {
    alpha2: 'NF',
    alpha3: 'NFK',
    currencyCode: 'AUD',
    name: 'Norfolk Island',
  },
  {
    alpha2: 'MP',
    alpha3: 'MNP',
    currencyCode: 'USD',
    name: 'Northern Mariana Islands',
  },
  {
    alpha2: 'NO',
    alpha3: 'NOR',
    currencyCode: 'EUR',
    name: 'Norway',
  },
  {
    alpha2: 'OM',
    alpha3: 'OMN',
    currencyCode: 'OMR',
    name: 'Oman',
  },
  {
    alpha2: 'PW',
    alpha3: 'PLW',
    currencyCode: 'USD',
    name: 'Palau',
  },
  {
    alpha2: 'PS',
    alpha3: 'PSE',
    currencyCode: 'JOD',
    name: 'Palestine, State of',
  },
  {
    alpha2: 'PA',
    alpha3: 'PAN',
    currencyCode: 'PAB',
    name: 'Panama',
  },
  {
    alpha2: 'PG',
    alpha3: 'PNG',
    currencyCode: 'PGK',
    name: 'Papua New Guinea',
  },
  {
    alpha2: 'PY',
    alpha3: 'PRY',
    currencyCode: 'PYG',
    name: 'Paraguay',
  },
  {
    alpha2: 'PE',
    alpha3: 'PER',
    currencyCode: 'PEN',
    name: 'Peru',
  },
  {
    alpha2: 'PH',
    alpha3: 'PHL',
    currencyCode: 'PHP',
    name: 'Philippines',
  },
  {
    alpha2: 'PN',
    alpha3: 'PCN',
    currencyCode: 'NZD',
    name: 'Pitcairn',
  },
  {
    alpha2: 'PL',
    alpha3: 'POL',
    currencyCode: 'PLN',
    name: 'Poland',
  },
  {
    alpha2: 'PT',
    alpha3: 'PRT',
    currencyCode: 'EUR',
    name: 'Portugal',
  },
  {
    alpha2: 'PR',
    alpha3: 'PRI',
    currencyCode: 'USD',
    name: 'Puerto Rico',
  },
  {
    alpha2: 'RO',
    alpha3: 'ROU',
    currencyCode: 'RON',
    name: 'Romania',
  },
  {
    alpha2: 'RW',
    alpha3: 'RWA',
    currencyCode: 'RWF',
    name: 'Rwanda',
  },
  {
    alpha2: 'RE',
    alpha3: 'REU',
    currencyCode: 'EUR',
    name: 'Réunion',
  },
  {
    alpha2: 'BL',
    alpha3: 'BLM',
    currencyCode: 'EUR',
    name: 'Saint Barthélemy',
  },
  {
    alpha2: 'KN',
    alpha3: 'KNA',
    currencyCode: 'XCD',
    name: 'Saint Kitts and Nevis',
  },
  {
    alpha2: 'LC',
    alpha3: 'LCA',
    currencyCode: 'XCD',
    name: 'Saint Lucia',
  },
  {
    alpha2: 'MF',
    alpha3: 'MAF',
    currencyCode: 'EUR',
    name: 'Saint Martin',
  },
  {
    alpha2: 'PM',
    alpha3: 'SPM',
    currencyCode: 'EUR',
    name: 'Saint Pierre And Miquelon',
  },
  {
    alpha2: 'VC',
    alpha3: 'VCT',
    currencyCode: 'XCD',
    name: 'Saint Vincent And The Grenadines',
  },
  {
    alpha2: 'WS',
    alpha3: 'WSM',
    currencyCode: 'EUR',
    name: 'Samoa',
  },
  {
    alpha2: 'SM',
    alpha3: 'SMR',
    currencyCode: 'EUR',
    name: 'San Marino',
  },
  {
    alpha2: 'ST',
    alpha3: 'STP',
    currencyCode: 'STN',
    name: 'Sao Tome and Principe',
  },
  {
    alpha2: 'RS',
    alpha3: 'SRB',
    currencyCode: 'RSD',
    name: 'Serbia',
  },
  {
    alpha2: 'SC',
    alpha3: 'SYC',
    currencyCode: 'SCR',
    name: 'Seychelles',
  },
  {
    alpha2: 'SG',
    alpha3: 'SGP',
    currencyCode: 'SGD',
    name: 'Singapore',
  },
  {
    alpha2: 'SK',
    alpha3: 'SVK',
    currencyCode: 'EUR',
    name: 'Slovakia',
  },
  {
    alpha2: 'SI',
    alpha3: 'SVN',
    currencyCode: 'EUR',
    name: 'Slovenia',
  },
  {
    alpha2: 'SB',
    alpha3: 'SLB',
    currencyCode: 'SBD',
    name: 'Solomon Islands',
  },
  {
    alpha2: 'KR',
    alpha3: 'KOR',
    currencyCode: 'KRW',
    name: 'South Korea',
  },
  {
    alpha2: 'ES',
    alpha3: 'ESP',
    currencyCode: 'EUR',
    name: 'Spain',
  },
  {
    alpha2: 'SR',
    alpha3: 'SUR',
    currencyCode: 'SRD',
    name: 'Suriname',
  },
  {
    alpha2: 'SJ',
    alpha3: 'SJM',
    currencyCode: 'NOK',
    name: 'Svalbard And Jan Mayen',
  },
  {
    alpha2: 'SE',
    alpha3: 'SWE',
    currencyCode: 'EUR',
    name: 'Sweden',
  },
  {
    alpha2: 'CH',
    alpha3: 'CHE',
    currencyCode: 'CHF',
    name: 'Switzerland',
  },
  {
    alpha2: 'TW',
    alpha3: 'TWN',
    currencyCode: 'TWD',
    name: 'Taiwan',
  },
  {
    alpha2: 'TJ',
    alpha3: 'TJK',
    currencyCode: 'TJS',
    name: 'Tajikistan',
  },
  {
    alpha2: 'TL',
    alpha3: 'TLS',
    currencyCode: 'USD',
    name: 'Timor-Leste',
  },
  {
    alpha2: 'TK',
    alpha3: 'TKL',
    currencyCode: 'NZD',
    name: 'Tokelau',
  },
  {
    alpha2: 'TO',
    alpha3: 'TON',
    currencyCode: 'TOP',
    name: 'Tonga',
  },
  {
    alpha2: 'TT',
    alpha3: 'TTO',
    currencyCode: 'TTD',
    name: 'Trinidad and Tobago',
  },
  {
    alpha2: 'TR',
    alpha3: 'TUR',
    currencyCode: 'TRY',
    name: 'Turkey',
  },
  {
    alpha2: 'TM',
    alpha3: 'TKM',
    currencyCode: 'TMT',
    name: 'Turkmenistan',
  },
  {
    alpha2: 'TC',
    alpha3: 'TCA',
    currencyCode: 'USD',
    name: 'Turks And Caicos Islands',
  },
  {
    alpha2: 'TV',
    alpha3: 'TUV',
    currencyCode: 'AUD',
    name: 'Tuvalu',
  },
  {
    alpha2: 'VI',
    alpha3: 'VIR',
    currencyCode: 'USD',
    name: 'U.S. Virgin Islands',
  },
  {
    alpha2: 'AE',
    alpha3: 'ARE',
    currencyCode: 'AED',
    name: 'United Arab Emirates',
  },
  {
    alpha2: 'GB',
    alpha3: 'GBR',
    currencyCode: 'GBP',
    name: 'United Kingdom',
  },
  {
    alpha2: 'US',
    alpha3: 'USA',
    currencyCode: 'USD',
    name: 'United States of America',
  },
  {
    alpha2: 'UY',
    alpha3: 'URY',
    currencyCode: 'UYU',
    name: 'Uruguay',
  },
  {
    alpha2: 'UZ',
    alpha3: 'UZB',
    currencyCode: 'UZS',
    name: 'Uzbekistan',
  },
  {
    alpha2: 'VA',
    alpha3: 'VAT',
    currencyCode: 'EUR',
    name: 'Vatican City State (Holy See)',
  },
  {
    alpha2: 'WF',
    alpha3: 'WLF',
    currencyCode: 'XPF',
    name: 'Wallis And Futuna',
  },
  {
    alpha2: 'EH',
    alpha3: 'ESH',
    currencyCode: 'MAD',
    name: 'Western Sahara',
  },
  {
    alpha2: 'AX',
    alpha3: 'ALA',
    currencyCode: 'EUR',
    name: 'Åland Islands',
  },
]

export const getTransakFiatCurrency = (countryCode?: string) => {
  const country = transakCountries.find(
    (item) => item.alpha2 === countryCode || item.alpha3 === countryCode,
  )

  return country?.currencyCode ?? 'USD'
}
