name: Publish Common Package
description: Publish the common package to NPM
inputs:
  NPM_ACCESS_TOKEN:
    description: 'The NPM access token'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install dependencies with pnpm
      shell: bash
      run: pnpm i

    - name: Prebuild with pnpm
      shell: bash
      run: pnpm prebuild

    - name: Build with pnpm
      shell: bash
      run: pnpm build:sdk

    - name: Publish package with pnpm
      shell: bash
      run: pnpm publish:npm
      working-directory: sdk/sdk-common
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_ACCESS_TOKEN }}
