export const MINUTE_IN_SECONDS = 60
export const HOUR_IN_SECONDS = MINUTE_IN_SECONDS * 60
export const DAY_IN_SECONDS = HOUR_IN_SECONDS * 24
export const WEEK_IN_SECONDS = DAY_IN_SECONDS * 7
export const YEAR_IN_SECONDS = DAY_IN_SECONDS * 365
export const LEAP_YEAR_IN_SECONDS = DAY_IN_SECONDS * 366
