/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Numeric = ColumnType<string, number | string, number | string>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface DailyStats {
  active_users: Generated<number>
  date: Timestamp
  points_earned: Generated<Numeric>
  referral_id: string
  total_deposits: Generated<Numeric>
}

export interface Migrations {
  applied_at: Generated<Timestamp | null>
  filename: string
  id: Generated<number>
}

export interface PointsConfig {
  created_at: Generated<Timestamp | null>
  description: string | null
  id: Generated<number>
  key: string
  updated_at: Generated<Timestamp | null>
  value: string
}

export interface Positions {
  chain: string
  current_deposit_usd: Generated<Numeric>
  fees_per_day_owner: Generated<Numeric>
  fees_per_day_referrer: Generated<Numeric>
  id: string
  is_volatile: Generated<boolean>
  last_synced_at: Timestamp | null
  user_id: string
}

export interface ProcessingCheckpoint {
  created_at: Generated<Timestamp | null>
  id: Generated<number>
  last_processed_timestamp: Timestamp
}

export interface ReferralCodes {
  active_users_count: Generated<number>
  created_at: Generated<Timestamp | null>
  custom_code: string | null
  fees_per_day: Generated<Numeric>
  id: string
  last_calculated_at: Timestamp | null
  points_per_day: Generated<Numeric>
  summer_per_day: Generated<Numeric>
  total_deposits_usd: Generated<Numeric>
  total_fees_claimed: Generated<Numeric>
  total_fees_earned: Generated<Numeric>
  total_points_claimed: Generated<Numeric>
  total_points_earned: Generated<Numeric>
  total_summer_claimed: Generated<Numeric>
  total_summer_earned: Generated<Numeric>
  type: string
  updated_at: Generated<Timestamp | null>
}

export interface RewardsDistributions {
  amount: Numeric
  created_at: Generated<Timestamp | null>
  description: string
  distribution_timestamp: Generated<Timestamp>
  id: Generated<number>
  referral_id: string
  type: string
}

export interface Users {
  created_at: Generated<Timestamp | null>
  id: string
  is_active: Generated<boolean>
  last_activity_at: Timestamp | null
  referral_chain: string | null
  referral_code: string | null
  referral_timestamp: Timestamp | null
  referrer_id: string | null
  updated_at: Generated<Timestamp | null>
}

export interface DB {
  daily_stats: DailyStats
  migrations: Migrations
  points_config: PointsConfig
  positions: Positions
  processing_checkpoint: ProcessingCheckpoint
  referral_codes: ReferralCodes
  rewards_distributions: RewardsDistributions
  users: Users
}
