name: Update Gateway lambdas (staging)

on:
  push:
    branches:
      - dev
      - TECH-2454-gha-changes
    paths:
      - 'apps/summerfi-api/**'
      - '.github/workflows/aws-staging-gateway.yaml'

defaults:
  run:
    working-directory: ./apps/summerfi-api

jobs:
  deploy_zip:
    name: Deploy lambda functions from zip
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_GW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_GW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.STAGING_AWS_REGION }}

      - name: Install dependencies
        run: |
              npm install

      - name: Create bundle
        run: |
              npm run build

      - name: Deploy portfolio-assets
        uses: appleboy/lambda-action@v0.1.9
        with:
          function_name: summer-fi-portfolio-assets-staging:current
          zip_file: ./apps/summerfi-api/artifacts/portfolio-assets.zip
          dry_run: false

      - name: Deploy portfolio-overview
        uses: appleboy/lambda-action@v0.1.9
        with:
          function_name: summer-fi-portfolio-overview-staging:current
          zip_file: ./apps/summerfi-api/artifacts/portfolio-overview.zip
          dry_run: false
      
      - name: Create cache invalidation
        run: |
              aws apigateway flush-stage-cache --rest-api-id ${{ secrets.STAGING_API_GW_ID }} --stage-name staging

