name: Update Gateway lambdas (prod)

on:
  push:
    branches:
      - main
    paths:
      - 'apps/summerfi-api/**'
      - '.github/workflows/aws-prod-gateway.yaml'

defaults:
  run:
    working-directory: ./apps/summerfi-api

jobs:
  deploy_zip:
    name: Deploy lambda functions from zip
    runs-on: ubuntu-latest
    environment: prod
    env:
      ASSETS_LAMBDA: summer-fi-portfolio-assets-prod
      OVERVIEW_LAMBDA: summer-fi-portfolio-overview-prod
      ASSETS_LAMBDA_ZIP_PATH: ./apps/summerfi-api/artifacts/portfolio-assets.zip
      OVERVIEW_LAMBDA_ZIP_PATH: ./apps/summerfi-api/artifacts/portfolio-overview.zip

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_GW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_GW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}

      - name: Install dependencies
        run: |
              npm install

      - name: Create bundle
        run: |
              npm run build

      - name: Deploy portfolio-assets
        id: assets-deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          function_name: ${{ env.ASSETS_LAMBDA }}
          zip_file: ${{ env.ASSETS_LAMBDA_ZIP_PATH }}
          dry_run: false

      - name: Deploy portfolio-overview
        id: overview-deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          function_name: ${{ env.OVERVIEW_LAMBDA }}
          zip_file: ${{ env.OVERVIEW_LAMBDA_ZIP_PATH }}
          dry_run: false

      - name: Retrieve the latest version of the Lambdas
        id: lambda-latest-version
        run: |
          assets_latest_version=$(aws lambda list-versions-by-function --function-name ${{ env.ASSETS_LAMBDA }} --query 'Versions[-1].Version' --output text)
          echo "assets_latest_version=$assets_latest_version" >> $GITHUB_OUTPUT
          overview_latest_version=$(aws lambda list-versions-by-function --function-name ${{ env.OVERVIEW_LAMBDA }} --query 'Versions[-1].Version' --output text)
          echo "overview_latest_version=$overview_latest_version" >> $GITHUB_OUTPUT

      - name: Update portfolio-assets Lambda Alias
        run: |
          aws lambda update-alias --function-name ${{ env.ASSETS_LAMBDA }} --name current --function-version ${{ steps.lambda-latest-version.outputs.assets_latest_version }}

      - name: Update portfolio-overview Lambda Alias
        run: |
          aws lambda update-alias --function-name ${{ env.OVERVIEW_LAMBDA }} --name current --function-version ${{ steps.lambda-latest-version.outputs.overview_latest_version }}
      
      - name: Create cache invalidation
        run: |
              aws apigateway flush-stage-cache --rest-api-id ${{ secrets.PROD_API_GW_ID }} --stage-name prod

