name: Deploy Earn Protocol Static Landing Page Staging
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-earn-protocol-landing-page:
    name: Build and deploy Earn Protocol Static Landing Page
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    environment: staging
    env:
      AWS_REGION: eu-central-1
      ENVIRONMENT_TAG: dev

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up turbo cache
        uses: rharkor/caching-for-turbo@v1.5

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.14.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Earn Protocol LP App Next.js Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/earn-protocol-landing-page/.next/cache
          key:
            ${{ runner.os }}-earn-protocol-landing-page-app-${{ hashFiles('pnpm-lock.yaml') }}-${{
            hashFiles('apps/earn-protocol-landing-page/**/*.ts',
            'apps/earn-protocol-landing-page/**/*.tsx') }}
          restore-keys:
            ${{ runner.os }}-earn-protocol-landing-page-app-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Extract commit hash
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "NEXT_PUBLIC_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Prebuild
        run: pnpm prebuild

      - name: Build
        run: pnpm build-earn-frontend-landing

      - name: Copy LP static files to a bucket 🪣
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws_region: ${{ env.AWS_REGION }}
          source: './apps/earn-protocol-landing-page/out'
          dest: 's3://${{ vars.LANDING_PAGE_BUCKET_NAME }}/'
          flags: --acl public-read --recursive

      - name: Invalidate CloudFront
        run: |
          AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${{ secrets.EARN_CF_DIST_ID }} --paths "/*"
