name: Deploy Earn Protocol App New Production
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-earn-protocol:
    name: Build and deploy Earn Protocol App
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    environment: production
    env:
      AWS_REGION: eu-central-1
      ENVIRONMENT_TAG: production
      SERVICE_NAME: summer-fi-earn-service-prod
      CLUSTER_NAME: summer-fi-earn-production
      CONFIG_URL: ${{ secrets.CONFIG_URL }}
      CONFIG_URL_EARN: ${{ secrets.CONFIG_URL_EARN }}
      CONFIG_URL_RAYS: ${{ secrets.CONFIG_URL_RAYS }}
      FUNCTIONS_API_URL: ${{ secrets.FUNCTIONS_API_URL }}
      BORROW_DB_READ_CONNECTION_STRING: ${{ secrets.NEW_BORROW_DB_READ_CONNECTION_STRING }}
      EARN_PROTOCOL_DB_CONNECTION_STRING: ${{ secrets.EARN_PROTOCOL_DB_CONNECTION_STRING }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      EARN_MIXPANEL_KEY: ${{ secrets.EARN_MIXPANEL_KEY }}
      NEXT_PUBLIC_EARN_MIXPANEL_KEY: ${{ secrets.NEXT_PUBLIC_EARN_MIXPANEL_KEY }}
      ACCOUNT_KIT_API_KEY: ${{ secrets.ACCOUNT_KIT_API_KEY }}
      FORECAST_API_URL: ${{ secrets.FORECAST_API_URL }}
      NEXT_PUBLIC_TRANSAK_API_KEY: ${{ secrets.NEXT_PUBLIC_TRANSAK_API_KEY }}
      NEXT_PUBLIC_TRANSAK_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_TRANSAK_ENVIRONMENT }}
      TRANSAK_SECRET: ${{ secrets.TRANSAK_SECRET }}
      SUBGRAPH_BASE: ${{ secrets.SUBGRAPH_BASE }}
      SDK_API_URL: ${{ vars.SDK_API_URL }}
      EARN_PROTOCOL_JWT_SECRET: ${{ secrets.EARN_PROTOCOL_JWT_SECRET }}
      EARN_PROTOCOL_JWT_CHALLENGE_SECRET: ${{ secrets.EARN_PROTOCOL_JWT_CHALLENGE_SECRET }}
      RPC_GATEWAY: ${{ secrets.RPC_GATEWAY }}
      TRM_API_KEY: ${{ secrets.TRM_API_KEY }}
      TALLY_API_KEY: ${{ secrets.TALLY_API_KEY }}
      NEWSLETTER_API_KEY: ${{ secrets.NEWSLETTER_API_KEY }}
      NEWSLETTER_PUBLICATION_ID: ${{ secrets.NEWSLETTER_PUBLICATION_ID }}
      NEWSLETTER_ENDPOINT: ${{ secrets.NEWSLETTER_ENDPOINT }}
      NEXT_TELEMETRY_DISABLED: ${{ secrets.NEXT_TELEMETRY_DISABLED }}
      SUMMER_DEPLOYMENT_CONFIG: ${{ vars.SUMMER_DEPLOYMENT_CONFIG }}
      EARN_PROTOCOL_UPDATE_TABLES_AUTH_TOKEN: ${{ secrets.EARN_PROTOCOL_UPDATE_TABLES_AUTH_TOKEN }}
      EARN_APP_URL: ${{ secrets.EARN_APP_URL }}
      BEACH_CLUB_REWARDS_DB_CONNECTION_STRING:
        ${{ secrets.BEACH_CLUB_REWARDS_DB_CONNECTION_STRING }}
      SECURE_PAGE_COOKIE_AUTH_TOKEN: ${{ secrets.SECURE_PAGE_COOKIE_AUTH_TOKEN }}
      GET_FORM_IO_KEY: ${{ secrets.GET_FORM_IO_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up turbo cache
        uses: rharkor/caching-for-turbo@v2.2.0
        with:
          max-age: 2mo
          cache-prefix: turbogha_
          provider: s3
          s3-bucket: staging-turbo-monorepo
          s3-region: eu-central-1
          s3-prefix: monorepo-cache/
          s3-endpoint: https://s3.amazonaws.com
          s3-access-key-id: ${{ secrets.TURBOREPO_S3_BUCKET_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.TURBOREPO_S3_BUCKET_SECRET_ACCESS_KEY }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.14.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Earn Protocol App Next.js Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/earn-protocol/.next/cache
          key:
            ${{ runner.os }}-earn-protocol-app-${{ hashFiles('pnpm-lock.yaml') }}-${{
            hashFiles('apps/earn-protocol/**/*.ts', 'apps/earn-protocol/**/*.tsx') }}
          restore-keys: ${{ runner.os }}-earn-protocol-app-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Establish VPN connection
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          echo 'Configuring the VPN...'
          echo "${{ secrets.NEW_VPN_CONFIG }}" > vpn-config.ovpn
          echo "${{ secrets.NEW_VPN_USERNAME }}" > vpn-credentials.txt
          echo "${{ secrets.NEW_VPN_PASSWORD }}" >> vpn-credentials.txt
          echo 'Connecting to the VPN...'
          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
          sleep 5

      - name: Check VPN connection
        env:
          SUMMER_DB_NAME: ${{ secrets.SUMMER_DB_NAME }}
          SUMMER_DB_HOST: ${{ secrets.SUMMER_DB_HOST }}
          SUMMER_DB_USER: ${{ secrets.SUMMER_DB_USER }}
          SUMMER_DB_PASSWORD: ${{ secrets.SUMMER_DB_PASSWORD }}
          PGCONNECT_TIMEOUT: 10
        run: |
          echo 'Checking the VPN connection...'
          sudo systemctl start postgresql.service
          PGPASSWORD=$SUMMER_DB_PASSWORD /usr/bin/psql -d $SUMMER_DB_NAME -U $SUMMER_DB_USER -h $SUMMER_DB_HOST -c 'SELECT 1;' > /dev/null
          STATUS_CODE=$?
          if ! [[ "$STATUS_CODE" = 0 ]]; then
            echo 'VPN connection failed'
            exit 1
          fi
          echo 'VPN connected!'

      - name: Extract commit hash
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "NEXT_PUBLIC_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Prebuild
        run: pnpm prebuild

      - name: Build
        run: pnpm build-earn-frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.BUILD_DEPLOY_OIDC_ROLE_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build docker image, copy build output and push to ECR
        id: build-image
        env:
          LATEST_TAG: latest
          ECR_REPO_NAME: summer-fi-earn-production
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          NEXT_PUBLIC_SHA: ${{ env.NEXT_PUBLIC_SHA }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -f apps/earn-protocol/docker/Dockerfile \
                       --build-arg EARN_PROTOCOL_DB_CONNECTION_STRING=${{ secrets.EARN_PROTOCOL_DB_CONNECTION_STRING }} \
                       --build-arg CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }} \
                       --build-arg CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} \
                       --build-arg CONTENTFUL_PREVIEW_ACCESS_TOKEN=${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }} \
                       --build-arg CONFIG_URL=${{ secrets.CONFIG_URL }} \
                       --build-arg CONFIG_URL_EARN=${{ secrets.CONFIG_URL_EARN }} \
                       --build-arg CONFIG_URL_RAYS=${{ secrets.CONFIG_URL_RAYS }} \
                       --build-arg FUNCTIONS_API_URL=${{ secrets.FUNCTIONS_API_URL }} \
                       --build-arg EARN_MIXPANEL_KEY=${{ secrets.EARN_MIXPANEL_KEY }} \
                       --build-arg SUBGRAPH_BASE=${{ secrets.SUBGRAPH_BASE }} \
                       --build-arg NEXT_PUBLIC_EARN_MIXPANEL_KEY=${{ secrets.NEXT_PUBLIC_EARN_MIXPANEL_KEY }} \
                       --build-arg ACCOUNT_KIT_API_KEY=${{ secrets.ACCOUNT_KIT_API_KEY }} \
                       --build-arg FORECAST_API_URL=${{ secrets.FORECAST_API_URL }} \
                       --build-arg NEXT_PUBLIC_TRANSAK_API_KEY=${{ secrets.NEXT_PUBLIC_TRANSAK_API_KEY }} \
                       --build-arg TRANSAK_SECRET=${{ secrets.TRANSAK_SECRET }} \
                       --build-arg EARN_PROTOCOL_JWT_SECRET=${{ secrets.EARN_PROTOCOL_JWT_SECRET }} \
                       --build-arg EARN_PROTOCOL_JWT_CHALLENGE_SECRET=${{ secrets.EARN_PROTOCOL_JWT_CHALLENGE_SECRET }} \
                       --build-arg NEXT_PUBLIC_TRANSAK_ENVIRONMENT=${{ secrets.NEXT_PUBLIC_TRANSAK_ENVIRONMENT }} \
                       --build-arg RPC_GATEWAY=${{ secrets.RPC_GATEWAY }} \
                       --build-arg TRM_API_KEY=${{ secrets.TRM_API_KEY }} \
                       --build-arg TALLY_API_KEY=${{ secrets.TALLY_API_KEY }} \
                       --build-arg NEWSLETTER_API_KEY=${{ secrets.NEWSLETTER_API_KEY }} \
                       --build-arg NEWSLETTER_PUBLICATION_ID=${{ secrets.NEWSLETTER_PUBLICATION_ID }} \
                       --build-arg NEWSLETTER_ENDPOINT=${{ secrets.NEWSLETTER_ENDPOINT }} \
                       --build-arg NEXT_TELEMETRY_DISABLED=${{ secrets.NEXT_TELEMETRY_DISABLED }} \
                       --build-arg SDK_API_URL=${{ env.SDK_API_URL }} \
                       --build-arg EARN_PROTOCOL_UPDATE_TABLES_AUTH_TOKEN=${{ secrets.EARN_PROTOCOL_UPDATE_TABLES_AUTH_TOKEN }} \
                       --build-arg EARN_APP_URL=${{ secrets.EARN_APP_URL }} \
                       --build-arg NEXT_PUBLIC_SHA=${{ env.NEXT_PUBLIC_SHA }} \
                       --build-arg ENVIRONMENT_TAG=${{ env.ENVIRONMENT_TAG }} \
                       --build-arg BEACH_CLUB_REWARDS_DB_CONNECTION_STRING=${{ secrets.BEACH_CLUB_REWARDS_DB_CONNECTION_STRING }} \
                       --build-arg SECURE_PAGE_COOKIE_AUTH_TOKEN=${{ secrets.SECURE_PAGE_COOKIE_AUTH_TOKEN }} \
                       --build-arg GET_FORM_IO_KEY=${{ secrets.GET_FORM_IO_KEY }} \
                       --cache-from type=registry,ref=189194422115.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/buildkit-test:cache \
                       -t $ECR_REGISTRY/$ECR_REPO_NAME:$NEXT_PUBLIC_SHA \
                       -t $ECR_REGISTRY/$ECR_REPO_NAME:$LATEST_TAG \
                       -t $ECR_REGISTRY/$ECR_REPO_NAME:$ENVIRONMENT_TAG \
                       ./apps/earn-protocol
          docker push $ECR_REGISTRY/$ECR_REPO_NAME --all-tags

      - name: Update ECS service with latest Docker image
        id: service-update
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service ${{ env.SERVICE_NAME }} --force-new-deployment --region $AWS_REGION

      - name: Invalidate CloudFront
        run: |
          AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${{ secrets.NEW_EARN_CF_DIST_ID }} --paths "/*"
