name: Publish SDK Packages Manually

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish from'
        required: true
        type: choice
        default: 'dev'
        options:
          - 'dev'
          - 'main'
      sdk_package:
        description: 'Select SDK package(s) to publish'
        required: true
        type: choice
        default: 'sdk-client'
        options:
          - 'all'
          - 'sdk-client'

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Publish Option: ${{ github.event.inputs.sdk_package }}"

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk_package: [sdk-client]
    env:
      CONFIG_URL: ${{ secrets.CONFIG_URL }}
      CONFIG_URL_EARN: ${{ secrets.CONFIG_URL_EARN }}
      SUBGRAPH_BASE: ${{ secrets.SUBGRAPH_BASE }}

    steps:
      - name: Checkout all files
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Publish the SDK ${{ matrix.sdk_package }} package to npmjs
        if: |
          github.event.inputs.sdk_package == 'all' || 
          github.event.inputs.sdk_package == matrix.sdk_package
        uses: ./.github/actions/publish-sdk-package
        with:
          sdk_package: ${{ matrix.sdk_package }}
          npm_access_token: ${{ secrets.NPM_ACCESS_TOKEN }}
