name: Publish Common Package

on:
  workflow_call:
    inputs:
      npm_access_token:
        required: true
        type: secret

jobs:
  publish-common-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        corepack: true

    - name: Install pnpm
      run: corepack enable && corepack prepare pnpm@latest --activate

    - name: Install dependencies with pnpm
      run: pnpm i

    - name: Build with pnpm
      run: pnpm build

    - name: Publish package with pnpm
      run: pnpm publish:npm
      working-directory: sdk/sdk-common
      env:
        NPM_ACCESS_TOKEN: ${{ inputs.npm_access_token }}
