### by Token
@tokenSymbol = SUMR
GET https://api.merkl.xyz/v4/campaigns
  ?tokenSymbol={{tokenSymbol}}

### by Opportunity
@opportunityId = 14664258849434578914
GET https://api.merkl.xyz/v4/opportunities/campaigns
  ?opportunityId={{opportunityId}}

### by Id
@campaignId = 6882942589603688379
GET https://api.merkl.xyz/v4/campaigns/{{campaignId}}
