### by Protocol Name
@name = SUMMER
https://api.merkl.xyz/v4/opportunities?name={{name}}

### by Tag
@tags = POOL
https://api.merkl.xyz/v4/opportunities?tags={{tags}}

### by OpportunityId
@opportunityId = 14664258849434578914
https://api.merkl.xyz/v4/opportunities/{{opportunityId}}

### by Identifier (rewards manager)
@identifier = 0xB1A851b8c70A4749408754d398702153A61DFc78
https://api.merkl.xyz/v4/opportunities?identifier={{identifier}}
